package com.lightningkite.services.telemetry

public object TelemetryKeys {
    public object Android {
        public val appState: TelemetryKey.OfString = TelemetryKey.OfString("android.app.state")
        public val osApiLevel: TelemetryKey.OfString = TelemetryKey.OfString("android.os.api_level")
        public val state: TelemetryKey.OfString = TelemetryKey.OfString("android.state")
    }
    public object App {
        public val buildId: TelemetryKey.OfString = TelemetryKey.OfString("app.build_id")
        public val crashId: TelemetryKey.OfString = TelemetryKey.OfString("app.crash.id")
        public val installationId: TelemetryKey.OfString = TelemetryKey.OfString("app.installation.id")
        public val jankFrameCount: TelemetryKey.OfLong = TelemetryKey.OfLong("app.jank.frame_count")
        public val jankPeriod: TelemetryKey.OfDouble = TelemetryKey.OfDouble("app.jank.period")
        public val jankThreshold: TelemetryKey.OfDouble = TelemetryKey.OfDouble("app.jank.threshold")
        public val screenCoordinateX: TelemetryKey.OfLong = TelemetryKey.OfLong("app.screen.coordinate.x")
        public val screenCoordinateY: TelemetryKey.OfLong = TelemetryKey.OfLong("app.screen.coordinate.y")
        public val screenId: TelemetryKey.OfString = TelemetryKey.OfString("app.screen.id")
        public val screenName: TelemetryKey.OfString = TelemetryKey.OfString("app.screen.name")
        public val widgetId: TelemetryKey.OfString = TelemetryKey.OfString("app.widget.id")
        public val widgetName: TelemetryKey.OfString = TelemetryKey.OfString("app.widget.name")
    }
    public object Artifact {
        public val attestationFilename: TelemetryKey.OfString = TelemetryKey.OfString("artifact.attestation.filename")
        public val attestationHash: TelemetryKey.OfString = TelemetryKey.OfString("artifact.attestation.hash")
        public val attestationId: TelemetryKey.OfString = TelemetryKey.OfString("artifact.attestation.id")
        public val filename: TelemetryKey.OfString = TelemetryKey.OfString("artifact.filename")
        public val hash: TelemetryKey.OfString = TelemetryKey.OfString("artifact.hash")
        public val purl: TelemetryKey.OfString = TelemetryKey.OfString("artifact.purl")
        public val version: TelemetryKey.OfString = TelemetryKey.OfString("artifact.version")
    }
    public object Aspnetcore {
        public val authenticationResult: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.authentication.result")
        public val authenticationScheme: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.authentication.scheme")
        public val authorizationPolicy: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.authorization.policy")
        public val authorizationResult: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.authorization.result")
        public val diagnosticsExceptionResult: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.diagnostics.exception.result")
        public val diagnosticsHandlerType: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.diagnostics.handler.type")
        public val identityErrorCode: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.error_code")
        public val identityPasswordCheckResult: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.password_check_result")
        public val identityResult: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.result")
        public val identitySignInResult: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.sign_in.result")
        public val identitySignInType: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.sign_in.type")
        public val identityTokenPurpose: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.token_purpose")
        public val identityTokenVerified: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.token_verified")
        public val identityUserUpdateType: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.user.update_type")
        public val identityUserType: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.identity.user_type")
        public val memoryPoolOwner: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.memory_pool.owner")
        public val rateLimitingPolicy: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.rate_limiting.policy")
        public val rateLimitingResult: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.rate_limiting.result")
        public val requestIsUnhandled: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("aspnetcore.request.is_unhandled")
        public val routingIsFallback: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("aspnetcore.routing.is_fallback")
        public val routingMatchStatus: TelemetryKey.OfString = TelemetryKey.OfString("aspnetcore.routing.match_status")
        public val signInIsPersistent: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("aspnetcore.sign_in.is_persistent")
        public val userIsAuthenticated: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("aspnetcore.user.is_authenticated")
    }
    public object Aws {
        public val bedrockGuardrailId: TelemetryKey.OfString = TelemetryKey.OfString("aws.bedrock.guardrail.id")
        public val bedrockKnowledgeBaseId: TelemetryKey.OfString = TelemetryKey.OfString("aws.bedrock.knowledge_base.id")
        public val dynamodbAttributeDefinitions: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.dynamodb.attribute_definitions")
        public val dynamodbAttributesToGet: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.dynamodb.attributes_to_get")
        public val dynamodbConsistentRead: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("aws.dynamodb.consistent_read")
        public val dynamodbConsumedCapacity: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.dynamodb.consumed_capacity")
        public val dynamodbCount: TelemetryKey.OfLong = TelemetryKey.OfLong("aws.dynamodb.count")
        public val dynamodbExclusiveStartTable: TelemetryKey.OfString = TelemetryKey.OfString("aws.dynamodb.exclusive_start_table")
        public val dynamodbGlobalSecondaryIndexUpdates: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.dynamodb.global_secondary_index_updates")
        public val dynamodbGlobalSecondaryIndexes: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.dynamodb.global_secondary_indexes")
        public val dynamodbIndexName: TelemetryKey.OfString = TelemetryKey.OfString("aws.dynamodb.index_name")
        public val dynamodbItemCollectionMetrics: TelemetryKey.OfString = TelemetryKey.OfString("aws.dynamodb.item_collection_metrics")
        public val dynamodbLimit: TelemetryKey.OfLong = TelemetryKey.OfLong("aws.dynamodb.limit")
        public val dynamodbLocalSecondaryIndexes: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.dynamodb.local_secondary_indexes")
        public val dynamodbProjection: TelemetryKey.OfString = TelemetryKey.OfString("aws.dynamodb.projection")
        public val dynamodbProvisionedReadCapacity: TelemetryKey.OfDouble = TelemetryKey.OfDouble("aws.dynamodb.provisioned_read_capacity")
        public val dynamodbProvisionedWriteCapacity: TelemetryKey.OfDouble = TelemetryKey.OfDouble("aws.dynamodb.provisioned_write_capacity")
        public val dynamodbScanForward: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("aws.dynamodb.scan_forward")
        public val dynamodbScannedCount: TelemetryKey.OfLong = TelemetryKey.OfLong("aws.dynamodb.scanned_count")
        public val dynamodbSegment: TelemetryKey.OfLong = TelemetryKey.OfLong("aws.dynamodb.segment")
        public val dynamodbSelect: TelemetryKey.OfString = TelemetryKey.OfString("aws.dynamodb.select")
        public val dynamodbTableCount: TelemetryKey.OfLong = TelemetryKey.OfLong("aws.dynamodb.table_count")
        public val dynamodbTableNames: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.dynamodb.table_names")
        public val dynamodbTotalSegments: TelemetryKey.OfLong = TelemetryKey.OfLong("aws.dynamodb.total_segments")
        public val ecsClusterArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.ecs.cluster.arn")
        public val ecsContainerArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.ecs.container.arn")
        public val ecsLaunchtype: TelemetryKey.OfString = TelemetryKey.OfString("aws.ecs.launchtype")
        public val ecsTaskArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.ecs.task.arn")
        public val ecsTaskFamily: TelemetryKey.OfString = TelemetryKey.OfString("aws.ecs.task.family")
        public val ecsTaskId: TelemetryKey.OfString = TelemetryKey.OfString("aws.ecs.task.id")
        public val ecsTaskRevision: TelemetryKey.OfString = TelemetryKey.OfString("aws.ecs.task.revision")
        public val eksClusterArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.eks.cluster.arn")
        public val extendedRequestId: TelemetryKey.OfString = TelemetryKey.OfString("aws.extended_request_id")
        public val kinesisStreamName: TelemetryKey.OfString = TelemetryKey.OfString("aws.kinesis.stream_name")
        public val lambdaInvokedArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.lambda.invoked_arn")
        public val lambdaResourceMappingId: TelemetryKey.OfString = TelemetryKey.OfString("aws.lambda.resource_mapping.id")
        public val logGroupArns: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.log.group.arns")
        public val logGroupNames: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.log.group.names")
        public val logStreamArns: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.log.stream.arns")
        public val logStreamNames: TelemetryKey.OfStringList = TelemetryKey.OfStringList("aws.log.stream.names")
        public val requestId: TelemetryKey.OfString = TelemetryKey.OfString("aws.request_id")
        public val s3Bucket: TelemetryKey.OfString = TelemetryKey.OfString("aws.s3.bucket")
        public val s3CopySource: TelemetryKey.OfString = TelemetryKey.OfString("aws.s3.copy_source")
        public val s3Delete: TelemetryKey.OfString = TelemetryKey.OfString("aws.s3.delete")
        public val s3Key: TelemetryKey.OfString = TelemetryKey.OfString("aws.s3.key")
        public val s3PartNumber: TelemetryKey.OfLong = TelemetryKey.OfLong("aws.s3.part_number")
        public val s3UploadId: TelemetryKey.OfString = TelemetryKey.OfString("aws.s3.upload_id")
        public val secretsmanagerSecretArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.secretsmanager.secret.arn")
        public val snsTopicArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.sns.topic.arn")
        public val sqsQueueUrl: TelemetryKey.OfString = TelemetryKey.OfString("aws.sqs.queue.url")
        public val stepFunctionsActivityArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.step_functions.activity.arn")
        public val stepFunctionsStateMachineArn: TelemetryKey.OfString = TelemetryKey.OfString("aws.step_functions.state_machine.arn")
    }
    public object Az {
        public val namespace: TelemetryKey.OfString = TelemetryKey.OfString("az.namespace")
        public val serviceRequestId: TelemetryKey.OfString = TelemetryKey.OfString("az.service_request_id")
    }
    public object Azure {
        public val clientId: TelemetryKey.OfString = TelemetryKey.OfString("azure.client.id")
        public val cosmosdbConnectionMode: TelemetryKey.OfString = TelemetryKey.OfString("azure.cosmosdb.connection.mode")
        public val cosmosdbConsistencyLevel: TelemetryKey.OfString = TelemetryKey.OfString("azure.cosmosdb.consistency.level")
        public val cosmosdbOperationContactedRegions: TelemetryKey.OfStringList = TelemetryKey.OfStringList("azure.cosmosdb.operation.contacted_regions")
        public val cosmosdbOperationRequestCharge: TelemetryKey.OfDouble = TelemetryKey.OfDouble("azure.cosmosdb.operation.request_charge")
        public val cosmosdbRequestBodySize: TelemetryKey.OfLong = TelemetryKey.OfLong("azure.cosmosdb.request.body.size")
        public val cosmosdbResponseSubStatusCode: TelemetryKey.OfLong = TelemetryKey.OfLong("azure.cosmosdb.response.sub_status_code")
        public val resourceProviderNamespace: TelemetryKey.OfString = TelemetryKey.OfString("azure.resource_provider.namespace")
        public val serviceRequestId: TelemetryKey.OfString = TelemetryKey.OfString("azure.service.request.id")
    }
    public object Browser {
        public val brands: TelemetryKey.OfStringList = TelemetryKey.OfStringList("browser.brands")
        public val documentUrlFull: TelemetryKey.OfString = TelemetryKey.OfString("browser.document.url.full")
        public val language: TelemetryKey.OfString = TelemetryKey.OfString("browser.language")
        public val mobile: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("browser.mobile")
        public val platform: TelemetryKey.OfString = TelemetryKey.OfString("browser.platform")
    }
    public object Cassandra {
        public val consistencyLevel: TelemetryKey.OfString = TelemetryKey.OfString("cassandra.consistency.level")
        public val coordinatorDc: TelemetryKey.OfString = TelemetryKey.OfString("cassandra.coordinator.dc")
        public val coordinatorId: TelemetryKey.OfString = TelemetryKey.OfString("cassandra.coordinator.id")
        public val pageSize: TelemetryKey.OfLong = TelemetryKey.OfLong("cassandra.page.size")
        public val queryIdempotent: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("cassandra.query.idempotent")
        public val speculativeExecutionCount: TelemetryKey.OfLong = TelemetryKey.OfLong("cassandra.speculative_execution.count")
    }
    public object Cicd {
        public val pipelineActionName: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.action.name")
        public val pipelineName: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.name")
        public val pipelineResult: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.result")
        public val pipelineRunId: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.run.id")
        public val pipelineRunState: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.run.state")
        public val pipelineRunUrlFull: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.run.url.full")
        public val pipelineTaskName: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.task.name")
        public val pipelineTaskRunId: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.task.run.id")
        public val pipelineTaskRunResult: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.task.run.result")
        public val pipelineTaskRunUrlFull: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.task.run.url.full")
        public val pipelineTaskType: TelemetryKey.OfString = TelemetryKey.OfString("cicd.pipeline.task.type")
        public val systemComponent: TelemetryKey.OfString = TelemetryKey.OfString("cicd.system.component")
        public val workerId: TelemetryKey.OfString = TelemetryKey.OfString("cicd.worker.id")
        public val workerName: TelemetryKey.OfString = TelemetryKey.OfString("cicd.worker.name")
        public val workerState: TelemetryKey.OfString = TelemetryKey.OfString("cicd.worker.state")
        public val workerUrlFull: TelemetryKey.OfString = TelemetryKey.OfString("cicd.worker.url.full")
    }
    public object Client {
        public val address: TelemetryKey.OfString = TelemetryKey.OfString("client.address")
        public val port: TelemetryKey.OfLong = TelemetryKey.OfLong("client.port")
    }
    public object Cloud {
        public val accountId: TelemetryKey.OfString = TelemetryKey.OfString("cloud.account.id")
        public val availabilityZone: TelemetryKey.OfString = TelemetryKey.OfString("cloud.availability_zone")
        public val platform: TelemetryKey.OfString = TelemetryKey.OfString("cloud.platform")
        public val provider: TelemetryKey.OfString = TelemetryKey.OfString("cloud.provider")
        public val region: TelemetryKey.OfString = TelemetryKey.OfString("cloud.region")
        public val resourceId: TelemetryKey.OfString = TelemetryKey.OfString("cloud.resource_id")
    }
    public object Cloudevents {
        public val eventId: TelemetryKey.OfString = TelemetryKey.OfString("cloudevents.event_id")
        public val eventSource: TelemetryKey.OfString = TelemetryKey.OfString("cloudevents.event_source")
        public val eventSpecVersion: TelemetryKey.OfString = TelemetryKey.OfString("cloudevents.event_spec_version")
        public val eventSubject: TelemetryKey.OfString = TelemetryKey.OfString("cloudevents.event_subject")
        public val eventType: TelemetryKey.OfString = TelemetryKey.OfString("cloudevents.event_type")
    }
    public object Cloudfoundry {
        public val appId: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.app.id")
        public val appInstanceId: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.app.instance.id")
        public val appName: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.app.name")
        public val orgId: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.org.id")
        public val orgName: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.org.name")
        public val processId: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.process.id")
        public val processType: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.process.type")
        public val spaceId: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.space.id")
        public val spaceName: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.space.name")
        public val systemId: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.system.id")
        public val systemInstanceId: TelemetryKey.OfString = TelemetryKey.OfString("cloudfoundry.system.instance.id")
    }
    public object Code {
        public val column: TelemetryKey.OfLong = TelemetryKey.OfLong("code.column")
        public val columnNumber: TelemetryKey.OfLong = TelemetryKey.OfLong("code.column.number")
        public val filePath: TelemetryKey.OfString = TelemetryKey.OfString("code.file.path")
        public val filepath: TelemetryKey.OfString = TelemetryKey.OfString("code.filepath")
        public val function: TelemetryKey.OfString = TelemetryKey.OfString("code.function")
        public val functionName: TelemetryKey.OfString = TelemetryKey.OfString("code.function.name")
        public val lineNumber: TelemetryKey.OfLong = TelemetryKey.OfLong("code.line.number")
        public val lineno: TelemetryKey.OfLong = TelemetryKey.OfLong("code.lineno")
        public val namespace: TelemetryKey.OfString = TelemetryKey.OfString("code.namespace")
        public val stacktrace: TelemetryKey.OfString = TelemetryKey.OfString("code.stacktrace")
    }
    public object Container {
        public val command: TelemetryKey.OfString = TelemetryKey.OfString("container.command")
        public val commandArgs: TelemetryKey.OfStringList = TelemetryKey.OfStringList("container.command_args")
        public val commandLine: TelemetryKey.OfString = TelemetryKey.OfString("container.command_line")
        public val cpuState: TelemetryKey.OfString = TelemetryKey.OfString("container.cpu.state")
        public val csiPluginName: TelemetryKey.OfString = TelemetryKey.OfString("container.csi.plugin.name")
        public val csiVolumeId: TelemetryKey.OfString = TelemetryKey.OfString("container.csi.volume.id")
        public val id: TelemetryKey.OfString = TelemetryKey.OfString("container.id")
        public val imageId: TelemetryKey.OfString = TelemetryKey.OfString("container.image.id")
        public val imageName: TelemetryKey.OfString = TelemetryKey.OfString("container.image.name")
        public val imageRepoDigests: TelemetryKey.OfStringList = TelemetryKey.OfStringList("container.image.repo_digests")
        public val imageTags: TelemetryKey.OfStringList = TelemetryKey.OfStringList("container.image.tags")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("container.name")
        public val runtime: TelemetryKey.OfString = TelemetryKey.OfString("container.runtime")
        public val runtimeDescription: TelemetryKey.OfString = TelemetryKey.OfString("container.runtime.description")
        public val runtimeName: TelemetryKey.OfString = TelemetryKey.OfString("container.runtime.name")
        public val runtimeVersion: TelemetryKey.OfString = TelemetryKey.OfString("container.runtime.version")
    }
    public object Cpu {
        public val logicalNumber: TelemetryKey.OfLong = TelemetryKey.OfLong("cpu.logical_number")
        public val mode: TelemetryKey.OfString = TelemetryKey.OfString("cpu.mode")
    }
    public object Cpython {
        public val gcGeneration: TelemetryKey.OfString = TelemetryKey.OfString("cpython.gc.generation")
    }
    public object Db {
        public val cassandraConsistencyLevel: TelemetryKey.OfString = TelemetryKey.OfString("db.cassandra.consistency_level")
        public val cassandraCoordinatorDc: TelemetryKey.OfString = TelemetryKey.OfString("db.cassandra.coordinator.dc")
        public val cassandraCoordinatorId: TelemetryKey.OfString = TelemetryKey.OfString("db.cassandra.coordinator.id")
        public val cassandraIdempotence: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("db.cassandra.idempotence")
        public val cassandraPageSize: TelemetryKey.OfLong = TelemetryKey.OfLong("db.cassandra.page_size")
        public val cassandraSpeculativeExecutionCount: TelemetryKey.OfLong = TelemetryKey.OfLong("db.cassandra.speculative_execution_count")
        public val cassandraTable: TelemetryKey.OfString = TelemetryKey.OfString("db.cassandra.table")
        public val clientConnectionPoolName: TelemetryKey.OfString = TelemetryKey.OfString("db.client.connection.pool.name")
        public val clientConnectionState: TelemetryKey.OfString = TelemetryKey.OfString("db.client.connection.state")
        public val clientConnectionsPoolName: TelemetryKey.OfString = TelemetryKey.OfString("db.client.connections.pool.name")
        public val clientConnectionsState: TelemetryKey.OfString = TelemetryKey.OfString("db.client.connections.state")
        public val collectionName: TelemetryKey.OfString = TelemetryKey.OfString("db.collection.name")
        public val connectionString: TelemetryKey.OfString = TelemetryKey.OfString("db.connection_string")
        public val cosmosdbClientId: TelemetryKey.OfString = TelemetryKey.OfString("db.cosmosdb.client_id")
        public val cosmosdbConnectionMode: TelemetryKey.OfString = TelemetryKey.OfString("db.cosmosdb.connection_mode")
        public val cosmosdbConsistencyLevel: TelemetryKey.OfString = TelemetryKey.OfString("db.cosmosdb.consistency_level")
        public val cosmosdbContainer: TelemetryKey.OfString = TelemetryKey.OfString("db.cosmosdb.container")
        public val cosmosdbOperationType: TelemetryKey.OfString = TelemetryKey.OfString("db.cosmosdb.operation_type")
        public val cosmosdbRegionsContacted: TelemetryKey.OfStringList = TelemetryKey.OfStringList("db.cosmosdb.regions_contacted")
        public val cosmosdbRequestCharge: TelemetryKey.OfDouble = TelemetryKey.OfDouble("db.cosmosdb.request_charge")
        public val cosmosdbRequestContentLength: TelemetryKey.OfLong = TelemetryKey.OfLong("db.cosmosdb.request_content_length")
        public val cosmosdbStatusCode: TelemetryKey.OfLong = TelemetryKey.OfLong("db.cosmosdb.status_code")
        public val cosmosdbSubStatusCode: TelemetryKey.OfLong = TelemetryKey.OfLong("db.cosmosdb.sub_status_code")
        public val elasticsearchClusterName: TelemetryKey.OfString = TelemetryKey.OfString("db.elasticsearch.cluster.name")
        public val elasticsearchNodeName: TelemetryKey.OfString = TelemetryKey.OfString("db.elasticsearch.node.name")
        public val instanceId: TelemetryKey.OfString = TelemetryKey.OfString("db.instance.id")
        public val jdbcDriverClassname: TelemetryKey.OfString = TelemetryKey.OfString("db.jdbc.driver_classname")
        public val mongodbCollection: TelemetryKey.OfString = TelemetryKey.OfString("db.mongodb.collection")
        public val mssqlInstanceName: TelemetryKey.OfString = TelemetryKey.OfString("db.mssql.instance_name")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("db.name")
        public val namespace: TelemetryKey.OfString = TelemetryKey.OfString("db.namespace")
        public val operation: TelemetryKey.OfString = TelemetryKey.OfString("db.operation")
        public val operationBatchSize: TelemetryKey.OfLong = TelemetryKey.OfLong("db.operation.batch.size")
        public val operationName: TelemetryKey.OfString = TelemetryKey.OfString("db.operation.name")
        public val querySummary: TelemetryKey.OfString = TelemetryKey.OfString("db.query.summary")
        public val queryText: TelemetryKey.OfString = TelemetryKey.OfString("db.query.text")
        public val redisDatabaseIndex: TelemetryKey.OfLong = TelemetryKey.OfLong("db.redis.database_index")
        public val responseReturnedRows: TelemetryKey.OfLong = TelemetryKey.OfLong("db.response.returned_rows")
        public val responseStatusCode: TelemetryKey.OfString = TelemetryKey.OfString("db.response.status_code")
        public val sqlTable: TelemetryKey.OfString = TelemetryKey.OfString("db.sql.table")
        public val statement: TelemetryKey.OfString = TelemetryKey.OfString("db.statement")
        public val storedProcedureName: TelemetryKey.OfString = TelemetryKey.OfString("db.stored_procedure.name")
        public val system: TelemetryKey.OfString = TelemetryKey.OfString("db.system")
        public val systemName: TelemetryKey.OfString = TelemetryKey.OfString("db.system.name")
        public val user: TelemetryKey.OfString = TelemetryKey.OfString("db.user")
    }
    public object Deployment {
        public val environment: TelemetryKey.OfString = TelemetryKey.OfString("deployment.environment")
        public val environmentName: TelemetryKey.OfString = TelemetryKey.OfString("deployment.environment.name")
        public val id: TelemetryKey.OfString = TelemetryKey.OfString("deployment.id")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("deployment.name")
        public val status: TelemetryKey.OfString = TelemetryKey.OfString("deployment.status")
    }
    public object Destination {
        public val address: TelemetryKey.OfString = TelemetryKey.OfString("destination.address")
        public val port: TelemetryKey.OfLong = TelemetryKey.OfLong("destination.port")
    }
    public object Device {
        public val id: TelemetryKey.OfString = TelemetryKey.OfString("device.id")
        public val manufacturer: TelemetryKey.OfString = TelemetryKey.OfString("device.manufacturer")
        public val modelIdentifier: TelemetryKey.OfString = TelemetryKey.OfString("device.model.identifier")
        public val modelName: TelemetryKey.OfString = TelemetryKey.OfString("device.model.name")
    }
    public object Disk {
        public val ioDirection: TelemetryKey.OfString = TelemetryKey.OfString("disk.io.direction")
    }
    public object Dns {
        public val answers: TelemetryKey.OfStringList = TelemetryKey.OfStringList("dns.answers")
        public val questionName: TelemetryKey.OfString = TelemetryKey.OfString("dns.question.name")
    }
    public object Dotnet {
        public val gcHeapGeneration: TelemetryKey.OfString = TelemetryKey.OfString("dotnet.gc.heap.generation")
    }
    public object Elasticsearch {
        public val nodeName: TelemetryKey.OfString = TelemetryKey.OfString("elasticsearch.node.name")
    }
    public object Enduser {
        public val id: TelemetryKey.OfString = TelemetryKey.OfString("enduser.id")
        public val pseudoId: TelemetryKey.OfString = TelemetryKey.OfString("enduser.pseudo.id")
        public val role: TelemetryKey.OfString = TelemetryKey.OfString("enduser.role")
        public val scope: TelemetryKey.OfString = TelemetryKey.OfString("enduser.scope")
    }
    public object Error {
        public val message: TelemetryKey.OfString = TelemetryKey.OfString("error.message")
        public val type: TelemetryKey.OfString = TelemetryKey.OfString("error.type")
    }
    public object Event {
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("event.name")
    }
    public object Exception {
        public val escaped: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("exception.escaped")
        public val message: TelemetryKey.OfString = TelemetryKey.OfString("exception.message")
        public val stacktrace: TelemetryKey.OfString = TelemetryKey.OfString("exception.stacktrace")
        public val type: TelemetryKey.OfString = TelemetryKey.OfString("exception.type")
    }
    public object Faas {
        public val coldstart: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("faas.coldstart")
        public val cron: TelemetryKey.OfString = TelemetryKey.OfString("faas.cron")
        public val documentCollection: TelemetryKey.OfString = TelemetryKey.OfString("faas.document.collection")
        public val documentName: TelemetryKey.OfString = TelemetryKey.OfString("faas.document.name")
        public val documentOperation: TelemetryKey.OfString = TelemetryKey.OfString("faas.document.operation")
        public val documentTime: TelemetryKey.OfString = TelemetryKey.OfString("faas.document.time")
        public val instance: TelemetryKey.OfString = TelemetryKey.OfString("faas.instance")
        public val invocationId: TelemetryKey.OfString = TelemetryKey.OfString("faas.invocation_id")
        public val invokedName: TelemetryKey.OfString = TelemetryKey.OfString("faas.invoked_name")
        public val invokedProvider: TelemetryKey.OfString = TelemetryKey.OfString("faas.invoked_provider")
        public val invokedRegion: TelemetryKey.OfString = TelemetryKey.OfString("faas.invoked_region")
        public val maxMemory: TelemetryKey.OfLong = TelemetryKey.OfLong("faas.max_memory")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("faas.name")
        public val time: TelemetryKey.OfString = TelemetryKey.OfString("faas.time")
        public val trigger: TelemetryKey.OfString = TelemetryKey.OfString("faas.trigger")
        public val version: TelemetryKey.OfString = TelemetryKey.OfString("faas.version")
    }
    public object FeatureFlag {
        public val contextId: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.context.id")
        public val errorMessage: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.error.message")
        public val evaluationErrorMessage: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.evaluation.error.message")
        public val evaluationReason: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.evaluation.reason")
        public val key: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.key")
        public val providerName: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.provider.name")
        public val resultReason: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.result.reason")
        public val resultVariant: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.result.variant")
        public val setId: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.set.id")
        public val variant: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.variant")
        public val version: TelemetryKey.OfString = TelemetryKey.OfString("feature_flag.version")
    }
    public object File {
        public val accessed: TelemetryKey.OfString = TelemetryKey.OfString("file.accessed")
        public val attributes: TelemetryKey.OfStringList = TelemetryKey.OfStringList("file.attributes")
        public val changed: TelemetryKey.OfString = TelemetryKey.OfString("file.changed")
        public val created: TelemetryKey.OfString = TelemetryKey.OfString("file.created")
        public val directory: TelemetryKey.OfString = TelemetryKey.OfString("file.directory")
        public val extension: TelemetryKey.OfString = TelemetryKey.OfString("file.extension")
        public val forkName: TelemetryKey.OfString = TelemetryKey.OfString("file.fork_name")
        public val groupId: TelemetryKey.OfString = TelemetryKey.OfString("file.group.id")
        public val groupName: TelemetryKey.OfString = TelemetryKey.OfString("file.group.name")
        public val inode: TelemetryKey.OfString = TelemetryKey.OfString("file.inode")
        public val lockMechanism: TelemetryKey.OfString = TelemetryKey.OfString("file.lock.mechanism")
        public val lockMode: TelemetryKey.OfString = TelemetryKey.OfString("file.lock.mode")
        public val lockType: TelemetryKey.OfString = TelemetryKey.OfString("file.lock.type")
        public val mode: TelemetryKey.OfString = TelemetryKey.OfString("file.mode")
        public val modified: TelemetryKey.OfString = TelemetryKey.OfString("file.modified")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("file.name")
        public val ownerId: TelemetryKey.OfString = TelemetryKey.OfString("file.owner.id")
        public val ownerName: TelemetryKey.OfString = TelemetryKey.OfString("file.owner.name")
        public val path: TelemetryKey.OfString = TelemetryKey.OfString("file.path")
        public val size: TelemetryKey.OfLong = TelemetryKey.OfLong("file.size")
        public val symbolicLinkTargetPath: TelemetryKey.OfString = TelemetryKey.OfString("file.symbolic_link.target_path")
    }
    public object Gcp {
        public val apphubApplicationContainer: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.application.container")
        public val apphubApplicationId: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.application.id")
        public val apphubApplicationLocation: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.application.location")
        public val apphubServiceCriticalityType: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.service.criticality_type")
        public val apphubServiceEnvironmentType: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.service.environment_type")
        public val apphubServiceId: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.service.id")
        public val apphubWorkloadCriticalityType: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.workload.criticality_type")
        public val apphubWorkloadEnvironmentType: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.workload.environment_type")
        public val apphubWorkloadId: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub.workload.id")
        public val apphubDestinationApplicationContainer: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.application.container")
        public val apphubDestinationApplicationId: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.application.id")
        public val apphubDestinationApplicationLocation: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.application.location")
        public val apphubDestinationServiceCriticalityType: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.service.criticality_type")
        public val apphubDestinationServiceEnvironmentType: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.service.environment_type")
        public val apphubDestinationServiceId: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.service.id")
        public val apphubDestinationWorkloadCriticalityType: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.workload.criticality_type")
        public val apphubDestinationWorkloadEnvironmentType: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.workload.environment_type")
        public val apphubDestinationWorkloadId: TelemetryKey.OfString = TelemetryKey.OfString("gcp.apphub_destination.workload.id")
        public val clientService: TelemetryKey.OfString = TelemetryKey.OfString("gcp.client.service")
        public val cloudRunJobExecution: TelemetryKey.OfString = TelemetryKey.OfString("gcp.cloud_run.job.execution")
        public val cloudRunJobTaskIndex: TelemetryKey.OfLong = TelemetryKey.OfLong("gcp.cloud_run.job.task_index")
        public val gceInstanceHostname: TelemetryKey.OfString = TelemetryKey.OfString("gcp.gce.instance.hostname")
        public val gceInstanceName: TelemetryKey.OfString = TelemetryKey.OfString("gcp.gce.instance.name")
        public val gceInstanceGroupManagerName: TelemetryKey.OfString = TelemetryKey.OfString("gcp.gce.instance_group_manager.name")
        public val gceInstanceGroupManagerRegion: TelemetryKey.OfString = TelemetryKey.OfString("gcp.gce.instance_group_manager.region")
        public val gceInstanceGroupManagerZone: TelemetryKey.OfString = TelemetryKey.OfString("gcp.gce.instance_group_manager.zone")
    }
    public object GenAi {
        public val agentDescription: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.agent.description")
        public val agentId: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.agent.id")
        public val agentName: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.agent.name")
        public val agentVersion: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.agent.version")
        public val completion: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.completion")
        public val conversationId: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.conversation.id")
        public val dataSourceId: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.data_source.id")
        public val embeddingsDimensionCount: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.embeddings.dimension.count")
        public val evaluationExplanation: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.evaluation.explanation")
        public val evaluationName: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.evaluation.name")
        public val evaluationScoreLabel: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.evaluation.score.label")
        public val evaluationScoreValue: TelemetryKey.OfDouble = TelemetryKey.OfDouble("gen_ai.evaluation.score.value")
        public val openaiRequestResponseFormat: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.openai.request.response_format")
        public val openaiRequestSeed: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.openai.request.seed")
        public val openaiRequestServiceTier: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.openai.request.service_tier")
        public val openaiResponseServiceTier: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.openai.response.service_tier")
        public val openaiResponseSystemFingerprint: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.openai.response.system_fingerprint")
        public val operationName: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.operation.name")
        public val outputType: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.output.type")
        public val prompt: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.prompt")
        public val promptName: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.prompt.name")
        public val providerName: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.provider.name")
        public val requestChoiceCount: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.request.choice.count")
        public val requestEncodingFormats: TelemetryKey.OfStringList = TelemetryKey.OfStringList("gen_ai.request.encoding_formats")
        public val requestFrequencyPenalty: TelemetryKey.OfDouble = TelemetryKey.OfDouble("gen_ai.request.frequency_penalty")
        public val requestMaxTokens: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.request.max_tokens")
        public val requestModel: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.request.model")
        public val requestPresencePenalty: TelemetryKey.OfDouble = TelemetryKey.OfDouble("gen_ai.request.presence_penalty")
        public val requestSeed: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.request.seed")
        public val requestStopSequences: TelemetryKey.OfStringList = TelemetryKey.OfStringList("gen_ai.request.stop_sequences")
        public val requestStream: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("gen_ai.request.stream")
        public val requestTemperature: TelemetryKey.OfDouble = TelemetryKey.OfDouble("gen_ai.request.temperature")
        public val requestTopK: TelemetryKey.OfDouble = TelemetryKey.OfDouble("gen_ai.request.top_k")
        public val requestTopP: TelemetryKey.OfDouble = TelemetryKey.OfDouble("gen_ai.request.top_p")
        public val responseFinishReasons: TelemetryKey.OfStringList = TelemetryKey.OfStringList("gen_ai.response.finish_reasons")
        public val responseId: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.response.id")
        public val responseModel: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.response.model")
        public val responseTimeToFirstChunk: TelemetryKey.OfDouble = TelemetryKey.OfDouble("gen_ai.response.time_to_first_chunk")
        public val retrievalQueryText: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.retrieval.query.text")
        public val system: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.system")
        public val tokenType: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.token.type")
        public val toolCallId: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.tool.call.id")
        public val toolDescription: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.tool.description")
        public val toolName: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.tool.name")
        public val toolType: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.tool.type")
        public val usageCacheCreationInputTokens: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.usage.cache_creation.input_tokens")
        public val usageCacheReadInputTokens: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.usage.cache_read.input_tokens")
        public val usageCompletionTokens: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.usage.completion_tokens")
        public val usageInputTokens: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.usage.input_tokens")
        public val usageOutputTokens: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.usage.output_tokens")
        public val usagePromptTokens: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.usage.prompt_tokens")
        public val usageReasoningOutputTokens: TelemetryKey.OfLong = TelemetryKey.OfLong("gen_ai.usage.reasoning.output_tokens")
        public val workflowName: TelemetryKey.OfString = TelemetryKey.OfString("gen_ai.workflow.name")
    }
    public object Geo {
        public val continentCode: TelemetryKey.OfString = TelemetryKey.OfString("geo.continent.code")
        public val countryIsoCode: TelemetryKey.OfString = TelemetryKey.OfString("geo.country.iso_code")
        public val localityName: TelemetryKey.OfString = TelemetryKey.OfString("geo.locality.name")
        public val locationLat: TelemetryKey.OfDouble = TelemetryKey.OfDouble("geo.location.lat")
        public val locationLon: TelemetryKey.OfDouble = TelemetryKey.OfDouble("geo.location.lon")
        public val postalCode: TelemetryKey.OfString = TelemetryKey.OfString("geo.postal_code")
        public val regionIsoCode: TelemetryKey.OfString = TelemetryKey.OfString("geo.region.iso_code")
    }
    public object Go {
        public val cpuDetailedState: TelemetryKey.OfString = TelemetryKey.OfString("go.cpu.detailed_state")
        public val cpuState: TelemetryKey.OfString = TelemetryKey.OfString("go.cpu.state")
        public val memoryDetailedType: TelemetryKey.OfString = TelemetryKey.OfString("go.memory.detailed_type")
        public val memoryType: TelemetryKey.OfString = TelemetryKey.OfString("go.memory.type")
    }
    public object Graphql {
        public val document: TelemetryKey.OfString = TelemetryKey.OfString("graphql.document")
        public val operationName: TelemetryKey.OfString = TelemetryKey.OfString("graphql.operation.name")
        public val operationType: TelemetryKey.OfString = TelemetryKey.OfString("graphql.operation.type")
    }
    public object Heroku {
        public val appId: TelemetryKey.OfString = TelemetryKey.OfString("heroku.app.id")
        public val releaseCommit: TelemetryKey.OfString = TelemetryKey.OfString("heroku.release.commit")
        public val releaseCreationTimestamp: TelemetryKey.OfString = TelemetryKey.OfString("heroku.release.creation_timestamp")
    }
    public object Host {
        public val arch: TelemetryKey.OfString = TelemetryKey.OfString("host.arch")
        public val cpuCacheL2Size: TelemetryKey.OfLong = TelemetryKey.OfLong("host.cpu.cache.l2.size")
        public val cpuFamily: TelemetryKey.OfString = TelemetryKey.OfString("host.cpu.family")
        public val cpuModelId: TelemetryKey.OfString = TelemetryKey.OfString("host.cpu.model.id")
        public val cpuModelName: TelemetryKey.OfString = TelemetryKey.OfString("host.cpu.model.name")
        public val cpuStepping: TelemetryKey.OfString = TelemetryKey.OfString("host.cpu.stepping")
        public val cpuVendorId: TelemetryKey.OfString = TelemetryKey.OfString("host.cpu.vendor.id")
        public val id: TelemetryKey.OfString = TelemetryKey.OfString("host.id")
        public val imageId: TelemetryKey.OfString = TelemetryKey.OfString("host.image.id")
        public val imageName: TelemetryKey.OfString = TelemetryKey.OfString("host.image.name")
        public val imageVersion: TelemetryKey.OfString = TelemetryKey.OfString("host.image.version")
        public val ip: TelemetryKey.OfStringList = TelemetryKey.OfStringList("host.ip")
        public val mac: TelemetryKey.OfStringList = TelemetryKey.OfStringList("host.mac")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("host.name")
        public val type: TelemetryKey.OfString = TelemetryKey.OfString("host.type")
    }
    public object Http {
        public val clientIp: TelemetryKey.OfString = TelemetryKey.OfString("http.client_ip")
        public val connectionState: TelemetryKey.OfString = TelemetryKey.OfString("http.connection.state")
        public val flavor: TelemetryKey.OfString = TelemetryKey.OfString("http.flavor")
        public val host: TelemetryKey.OfString = TelemetryKey.OfString("http.host")
        public val method: TelemetryKey.OfString = TelemetryKey.OfString("http.method")
        public val requestBodySize: TelemetryKey.OfLong = TelemetryKey.OfLong("http.request.body.size")
        public val requestMethod: TelemetryKey.OfString = TelemetryKey.OfString("http.request.method")
        public val requestMethodOriginal: TelemetryKey.OfString = TelemetryKey.OfString("http.request.method_original")
        public val requestResendCount: TelemetryKey.OfLong = TelemetryKey.OfLong("http.request.resend_count")
        public val requestSize: TelemetryKey.OfLong = TelemetryKey.OfLong("http.request.size")
        public val requestContentLength: TelemetryKey.OfLong = TelemetryKey.OfLong("http.request_content_length")
        public val requestContentLengthUncompressed: TelemetryKey.OfLong = TelemetryKey.OfLong("http.request_content_length_uncompressed")
        public val responseBodySize: TelemetryKey.OfLong = TelemetryKey.OfLong("http.response.body.size")
        public val responseSize: TelemetryKey.OfLong = TelemetryKey.OfLong("http.response.size")
        public val responseStatusCode: TelemetryKey.OfLong = TelemetryKey.OfLong("http.response.status_code")
        public val responseContentLength: TelemetryKey.OfLong = TelemetryKey.OfLong("http.response_content_length")
        public val responseContentLengthUncompressed: TelemetryKey.OfLong = TelemetryKey.OfLong("http.response_content_length_uncompressed")
        public val route: TelemetryKey.OfString = TelemetryKey.OfString("http.route")
        public val scheme: TelemetryKey.OfString = TelemetryKey.OfString("http.scheme")
        public val serverName: TelemetryKey.OfString = TelemetryKey.OfString("http.server_name")
        public val statusCode: TelemetryKey.OfLong = TelemetryKey.OfLong("http.status_code")
        public val target: TelemetryKey.OfString = TelemetryKey.OfString("http.target")
        public val url: TelemetryKey.OfString = TelemetryKey.OfString("http.url")
        public val userAgent: TelemetryKey.OfString = TelemetryKey.OfString("http.user_agent")
    }
    public object Hw {
        public val batteryCapacity: TelemetryKey.OfString = TelemetryKey.OfString("hw.battery.capacity")
        public val batteryChemistry: TelemetryKey.OfString = TelemetryKey.OfString("hw.battery.chemistry")
        public val batteryState: TelemetryKey.OfString = TelemetryKey.OfString("hw.battery.state")
        public val biosVersion: TelemetryKey.OfString = TelemetryKey.OfString("hw.bios_version")
        public val driverVersion: TelemetryKey.OfString = TelemetryKey.OfString("hw.driver_version")
        public val enclosureType: TelemetryKey.OfString = TelemetryKey.OfString("hw.enclosure.type")
        public val firmwareVersion: TelemetryKey.OfString = TelemetryKey.OfString("hw.firmware_version")
        public val gpuTask: TelemetryKey.OfString = TelemetryKey.OfString("hw.gpu.task")
        public val id: TelemetryKey.OfString = TelemetryKey.OfString("hw.id")
        public val limitType: TelemetryKey.OfString = TelemetryKey.OfString("hw.limit_type")
        public val logicalDiskRaidLevel: TelemetryKey.OfString = TelemetryKey.OfString("hw.logical_disk.raid_level")
        public val logicalDiskState: TelemetryKey.OfString = TelemetryKey.OfString("hw.logical_disk.state")
        public val memoryType: TelemetryKey.OfString = TelemetryKey.OfString("hw.memory.type")
        public val model: TelemetryKey.OfString = TelemetryKey.OfString("hw.model")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("hw.name")
        public val networkLogicalAddresses: TelemetryKey.OfStringList = TelemetryKey.OfStringList("hw.network.logical_addresses")
        public val networkPhysicalAddress: TelemetryKey.OfString = TelemetryKey.OfString("hw.network.physical_address")
        public val parent: TelemetryKey.OfString = TelemetryKey.OfString("hw.parent")
        public val physicalDiskSmartAttribute: TelemetryKey.OfString = TelemetryKey.OfString("hw.physical_disk.smart_attribute")
        public val physicalDiskState: TelemetryKey.OfString = TelemetryKey.OfString("hw.physical_disk.state")
        public val physicalDiskType: TelemetryKey.OfString = TelemetryKey.OfString("hw.physical_disk.type")
        public val sensorLocation: TelemetryKey.OfString = TelemetryKey.OfString("hw.sensor_location")
        public val serialNumber: TelemetryKey.OfString = TelemetryKey.OfString("hw.serial_number")
        public val state: TelemetryKey.OfString = TelemetryKey.OfString("hw.state")
        public val tapeDriveOperationType: TelemetryKey.OfString = TelemetryKey.OfString("hw.tape_drive.operation_type")
        public val type: TelemetryKey.OfString = TelemetryKey.OfString("hw.type")
        public val vendor: TelemetryKey.OfString = TelemetryKey.OfString("hw.vendor")
    }
    public object Ios {
        public val appState: TelemetryKey.OfString = TelemetryKey.OfString("ios.app.state")
        public val state: TelemetryKey.OfString = TelemetryKey.OfString("ios.state")
    }
    public object Jsonrpc {
        public val protocolVersion: TelemetryKey.OfString = TelemetryKey.OfString("jsonrpc.protocol.version")
        public val requestId: TelemetryKey.OfString = TelemetryKey.OfString("jsonrpc.request.id")
    }
    public object Jvm {
        public val bufferPoolName: TelemetryKey.OfString = TelemetryKey.OfString("jvm.buffer.pool.name")
        public val gcAction: TelemetryKey.OfString = TelemetryKey.OfString("jvm.gc.action")
        public val gcCause: TelemetryKey.OfString = TelemetryKey.OfString("jvm.gc.cause")
        public val gcName: TelemetryKey.OfString = TelemetryKey.OfString("jvm.gc.name")
        public val memoryPoolName: TelemetryKey.OfString = TelemetryKey.OfString("jvm.memory.pool.name")
        public val memoryType: TelemetryKey.OfString = TelemetryKey.OfString("jvm.memory.type")
        public val threadDaemon: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("jvm.thread.daemon")
        public val threadState: TelemetryKey.OfString = TelemetryKey.OfString("jvm.thread.state")
    }
    public object K8s {
        public val clusterName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.cluster.name")
        public val clusterUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.cluster.uid")
        public val containerEphemeralStorageFsType: TelemetryKey.OfString = TelemetryKey.OfString("k8s.container.ephemeral_storage.fs_type")
        public val containerName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.container.name")
        public val containerRestartCount: TelemetryKey.OfLong = TelemetryKey.OfLong("k8s.container.restart_count")
        public val containerStatusLastTerminatedReason: TelemetryKey.OfString = TelemetryKey.OfString("k8s.container.status.last_terminated_reason")
        public val containerStatusReason: TelemetryKey.OfString = TelemetryKey.OfString("k8s.container.status.reason")
        public val containerStatusState: TelemetryKey.OfString = TelemetryKey.OfString("k8s.container.status.state")
        public val cronjobName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.cronjob.name")
        public val cronjobUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.cronjob.uid")
        public val daemonsetName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.daemonset.name")
        public val daemonsetUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.daemonset.uid")
        public val deploymentName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.deployment.name")
        public val deploymentUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.deployment.uid")
        public val hpaMetricType: TelemetryKey.OfString = TelemetryKey.OfString("k8s.hpa.metric.type")
        public val hpaName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.hpa.name")
        public val hpaScaletargetrefApiVersion: TelemetryKey.OfString = TelemetryKey.OfString("k8s.hpa.scaletargetref.api_version")
        public val hpaScaletargetrefKind: TelemetryKey.OfString = TelemetryKey.OfString("k8s.hpa.scaletargetref.kind")
        public val hpaScaletargetrefName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.hpa.scaletargetref.name")
        public val hpaUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.hpa.uid")
        public val hugepageSize: TelemetryKey.OfString = TelemetryKey.OfString("k8s.hugepage.size")
        public val jobName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.job.name")
        public val jobUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.job.uid")
        public val namespaceName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.namespace.name")
        public val namespacePhase: TelemetryKey.OfString = TelemetryKey.OfString("k8s.namespace.phase")
        public val nodeConditionStatus: TelemetryKey.OfString = TelemetryKey.OfString("k8s.node.condition.status")
        public val nodeConditionType: TelemetryKey.OfString = TelemetryKey.OfString("k8s.node.condition.type")
        public val nodeName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.node.name")
        public val nodeSystemContainerName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.node.system_container.name")
        public val nodeUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.node.uid")
        public val persistentvolumeName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.persistentvolume.name")
        public val persistentvolumeReclaimPolicy: TelemetryKey.OfString = TelemetryKey.OfString("k8s.persistentvolume.reclaim_policy")
        public val persistentvolumeStatusPhase: TelemetryKey.OfString = TelemetryKey.OfString("k8s.persistentvolume.status.phase")
        public val persistentvolumeUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.persistentvolume.uid")
        public val persistentvolumeclaimName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.persistentvolumeclaim.name")
        public val persistentvolumeclaimStatusPhase: TelemetryKey.OfString = TelemetryKey.OfString("k8s.persistentvolumeclaim.status.phase")
        public val persistentvolumeclaimUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.persistentvolumeclaim.uid")
        public val podHostname: TelemetryKey.OfString = TelemetryKey.OfString("k8s.pod.hostname")
        public val podIp: TelemetryKey.OfString = TelemetryKey.OfString("k8s.pod.ip")
        public val podName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.pod.name")
        public val podStartTime: TelemetryKey.OfString = TelemetryKey.OfString("k8s.pod.start_time")
        public val podStatusPhase: TelemetryKey.OfString = TelemetryKey.OfString("k8s.pod.status.phase")
        public val podStatusReason: TelemetryKey.OfString = TelemetryKey.OfString("k8s.pod.status.reason")
        public val podUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.pod.uid")
        public val replicasetName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.replicaset.name")
        public val replicasetUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.replicaset.uid")
        public val replicationcontrollerName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.replicationcontroller.name")
        public val replicationcontrollerUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.replicationcontroller.uid")
        public val resourcequotaName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.resourcequota.name")
        public val resourcequotaResourceName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.resourcequota.resource_name")
        public val resourcequotaUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.resourcequota.uid")
        public val serviceEndpointAddressType: TelemetryKey.OfString = TelemetryKey.OfString("k8s.service.endpoint.address_type")
        public val serviceEndpointCondition: TelemetryKey.OfString = TelemetryKey.OfString("k8s.service.endpoint.condition")
        public val serviceEndpointZone: TelemetryKey.OfString = TelemetryKey.OfString("k8s.service.endpoint.zone")
        public val serviceName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.service.name")
        public val servicePublishNotReadyAddresses: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("k8s.service.publish_not_ready_addresses")
        public val serviceTrafficDistribution: TelemetryKey.OfString = TelemetryKey.OfString("k8s.service.traffic_distribution")
        public val serviceType: TelemetryKey.OfString = TelemetryKey.OfString("k8s.service.type")
        public val serviceUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.service.uid")
        public val statefulsetName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.statefulset.name")
        public val statefulsetUid: TelemetryKey.OfString = TelemetryKey.OfString("k8s.statefulset.uid")
        public val storageclassName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.storageclass.name")
        public val volumeName: TelemetryKey.OfString = TelemetryKey.OfString("k8s.volume.name")
        public val volumeType: TelemetryKey.OfString = TelemetryKey.OfString("k8s.volume.type")
    }
    public object Linux {
        public val memorySlabState: TelemetryKey.OfString = TelemetryKey.OfString("linux.memory.slab.state")
    }
    public object Log {
        public val fileName: TelemetryKey.OfString = TelemetryKey.OfString("log.file.name")
        public val fileNameResolved: TelemetryKey.OfString = TelemetryKey.OfString("log.file.name_resolved")
        public val filePath: TelemetryKey.OfString = TelemetryKey.OfString("log.file.path")
        public val filePathResolved: TelemetryKey.OfString = TelemetryKey.OfString("log.file.path_resolved")
        public val iostream: TelemetryKey.OfString = TelemetryKey.OfString("log.iostream")
        public val recordOriginal: TelemetryKey.OfString = TelemetryKey.OfString("log.record.original")
        public val recordUid: TelemetryKey.OfString = TelemetryKey.OfString("log.record.uid")
    }
    public object Mainframe {
        public val lparName: TelemetryKey.OfString = TelemetryKey.OfString("mainframe.lpar.name")
    }
    public object Mcp {
        public val methodName: TelemetryKey.OfString = TelemetryKey.OfString("mcp.method.name")
        public val protocolVersion: TelemetryKey.OfString = TelemetryKey.OfString("mcp.protocol.version")
        public val resourceUri: TelemetryKey.OfString = TelemetryKey.OfString("mcp.resource.uri")
        public val sessionId: TelemetryKey.OfString = TelemetryKey.OfString("mcp.session.id")
    }
    public object Message {
        public val compressedSize: TelemetryKey.OfLong = TelemetryKey.OfLong("message.compressed_size")
        public val id: TelemetryKey.OfLong = TelemetryKey.OfLong("message.id")
        public val type: TelemetryKey.OfString = TelemetryKey.OfString("message.type")
        public val uncompressedSize: TelemetryKey.OfLong = TelemetryKey.OfLong("message.uncompressed_size")
    }
    public object Messaging {
        public val batchMessageCount: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.batch.message_count")
        public val clientId: TelemetryKey.OfString = TelemetryKey.OfString("messaging.client_id")
        public val consumerGroupName: TelemetryKey.OfString = TelemetryKey.OfString("messaging.consumer.group.name")
        public val destinationAnonymous: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("messaging.destination.anonymous")
        public val destinationName: TelemetryKey.OfString = TelemetryKey.OfString("messaging.destination.name")
        public val destinationPartitionId: TelemetryKey.OfString = TelemetryKey.OfString("messaging.destination.partition.id")
        public val destinationSubscriptionName: TelemetryKey.OfString = TelemetryKey.OfString("messaging.destination.subscription.name")
        public val destinationTemplate: TelemetryKey.OfString = TelemetryKey.OfString("messaging.destination.template")
        public val destinationTemporary: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("messaging.destination.temporary")
        public val destinationPublishAnonymous: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("messaging.destination_publish.anonymous")
        public val destinationPublishName: TelemetryKey.OfString = TelemetryKey.OfString("messaging.destination_publish.name")
        public val eventhubsConsumerGroup: TelemetryKey.OfString = TelemetryKey.OfString("messaging.eventhubs.consumer.group")
        public val eventhubsMessageEnqueuedTime: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.eventhubs.message.enqueued_time")
        public val gcpPubsubMessageAckDeadline: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.gcp_pubsub.message.ack_deadline")
        public val gcpPubsubMessageAckId: TelemetryKey.OfString = TelemetryKey.OfString("messaging.gcp_pubsub.message.ack_id")
        public val gcpPubsubMessageDeliveryAttempt: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.gcp_pubsub.message.delivery_attempt")
        public val gcpPubsubMessageOrderingKey: TelemetryKey.OfString = TelemetryKey.OfString("messaging.gcp_pubsub.message.ordering_key")
        public val kafkaConsumerGroup: TelemetryKey.OfString = TelemetryKey.OfString("messaging.kafka.consumer.group")
        public val kafkaDestinationPartition: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.kafka.destination.partition")
        public val kafkaMessageKey: TelemetryKey.OfString = TelemetryKey.OfString("messaging.kafka.message.key")
        public val kafkaMessageOffset: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.kafka.message.offset")
        public val kafkaMessageTombstone: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("messaging.kafka.message.tombstone")
        public val kafkaOffset: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.kafka.offset")
        public val messageBodySize: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.message.body.size")
        public val messageConversationId: TelemetryKey.OfString = TelemetryKey.OfString("messaging.message.conversation_id")
        public val messageEnvelopeSize: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.message.envelope.size")
        public val messageId: TelemetryKey.OfString = TelemetryKey.OfString("messaging.message.id")
        public val operation: TelemetryKey.OfString = TelemetryKey.OfString("messaging.operation")
        public val operationName: TelemetryKey.OfString = TelemetryKey.OfString("messaging.operation.name")
        public val operationType: TelemetryKey.OfString = TelemetryKey.OfString("messaging.operation.type")
        public val rabbitmqDestinationRoutingKey: TelemetryKey.OfString = TelemetryKey.OfString("messaging.rabbitmq.destination.routing_key")
        public val rabbitmqMessageDeliveryTag: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.rabbitmq.message.delivery_tag")
        public val rocketmqClientGroup: TelemetryKey.OfString = TelemetryKey.OfString("messaging.rocketmq.client_group")
        public val rocketmqConsumptionModel: TelemetryKey.OfString = TelemetryKey.OfString("messaging.rocketmq.consumption_model")
        public val rocketmqMessageDelayTimeLevel: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.rocketmq.message.delay_time_level")
        public val rocketmqMessageDeliveryTimestamp: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.rocketmq.message.delivery_timestamp")
        public val rocketmqMessageGroup: TelemetryKey.OfString = TelemetryKey.OfString("messaging.rocketmq.message.group")
        public val rocketmqMessageKeys: TelemetryKey.OfStringList = TelemetryKey.OfStringList("messaging.rocketmq.message.keys")
        public val rocketmqMessageTag: TelemetryKey.OfString = TelemetryKey.OfString("messaging.rocketmq.message.tag")
        public val rocketmqMessageType: TelemetryKey.OfString = TelemetryKey.OfString("messaging.rocketmq.message.type")
        public val rocketmqNamespace: TelemetryKey.OfString = TelemetryKey.OfString("messaging.rocketmq.namespace")
        public val servicebusDestinationSubscriptionName: TelemetryKey.OfString = TelemetryKey.OfString("messaging.servicebus.destination.subscription_name")
        public val servicebusDispositionStatus: TelemetryKey.OfString = TelemetryKey.OfString("messaging.servicebus.disposition_status")
        public val servicebusMessageDeliveryCount: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.servicebus.message.delivery_count")
        public val servicebusMessageEnqueuedTime: TelemetryKey.OfLong = TelemetryKey.OfLong("messaging.servicebus.message.enqueued_time")
        public val system: TelemetryKey.OfString = TelemetryKey.OfString("messaging.system")
    }
    public object Net {
        public val hostIp: TelemetryKey.OfString = TelemetryKey.OfString("net.host.ip")
        public val hostName: TelemetryKey.OfString = TelemetryKey.OfString("net.host.name")
        public val hostPort: TelemetryKey.OfLong = TelemetryKey.OfLong("net.host.port")
        public val peerIp: TelemetryKey.OfString = TelemetryKey.OfString("net.peer.ip")
        public val peerName: TelemetryKey.OfString = TelemetryKey.OfString("net.peer.name")
        public val peerPort: TelemetryKey.OfLong = TelemetryKey.OfLong("net.peer.port")
        public val protocolName: TelemetryKey.OfString = TelemetryKey.OfString("net.protocol.name")
        public val protocolVersion: TelemetryKey.OfString = TelemetryKey.OfString("net.protocol.version")
        public val sockFamily: TelemetryKey.OfString = TelemetryKey.OfString("net.sock.family")
        public val sockHostAddr: TelemetryKey.OfString = TelemetryKey.OfString("net.sock.host.addr")
        public val sockHostPort: TelemetryKey.OfLong = TelemetryKey.OfLong("net.sock.host.port")
        public val sockPeerAddr: TelemetryKey.OfString = TelemetryKey.OfString("net.sock.peer.addr")
        public val sockPeerName: TelemetryKey.OfString = TelemetryKey.OfString("net.sock.peer.name")
        public val sockPeerPort: TelemetryKey.OfLong = TelemetryKey.OfLong("net.sock.peer.port")
        public val transport: TelemetryKey.OfString = TelemetryKey.OfString("net.transport")
    }
    public object Network {
        public val carrierIcc: TelemetryKey.OfString = TelemetryKey.OfString("network.carrier.icc")
        public val carrierMcc: TelemetryKey.OfString = TelemetryKey.OfString("network.carrier.mcc")
        public val carrierMnc: TelemetryKey.OfString = TelemetryKey.OfString("network.carrier.mnc")
        public val carrierName: TelemetryKey.OfString = TelemetryKey.OfString("network.carrier.name")
        public val connectionState: TelemetryKey.OfString = TelemetryKey.OfString("network.connection.state")
        public val connectionSubtype: TelemetryKey.OfString = TelemetryKey.OfString("network.connection.subtype")
        public val connectionType: TelemetryKey.OfString = TelemetryKey.OfString("network.connection.type")
        public val interfaceName: TelemetryKey.OfString = TelemetryKey.OfString("network.interface.name")
        public val ioDirection: TelemetryKey.OfString = TelemetryKey.OfString("network.io.direction")
        public val localAddress: TelemetryKey.OfString = TelemetryKey.OfString("network.local.address")
        public val localPort: TelemetryKey.OfLong = TelemetryKey.OfLong("network.local.port")
        public val peerAddress: TelemetryKey.OfString = TelemetryKey.OfString("network.peer.address")
        public val peerPort: TelemetryKey.OfLong = TelemetryKey.OfLong("network.peer.port")
        public val protocolName: TelemetryKey.OfString = TelemetryKey.OfString("network.protocol.name")
        public val protocolVersion: TelemetryKey.OfString = TelemetryKey.OfString("network.protocol.version")
        public val transport: TelemetryKey.OfString = TelemetryKey.OfString("network.transport")
        public val type: TelemetryKey.OfString = TelemetryKey.OfString("network.type")
    }
    public object Nfs {
        public val operationName: TelemetryKey.OfString = TelemetryKey.OfString("nfs.operation.name")
        public val serverRepcacheStatus: TelemetryKey.OfString = TelemetryKey.OfString("nfs.server.repcache.status")
    }
    public object Nodejs {
        public val eventloopState: TelemetryKey.OfString = TelemetryKey.OfString("nodejs.eventloop.state")
    }
    public object Oci {
        public val manifestDigest: TelemetryKey.OfString = TelemetryKey.OfString("oci.manifest.digest")
    }
    public object OncRpc {
        public val procedureName: TelemetryKey.OfString = TelemetryKey.OfString("onc_rpc.procedure.name")
        public val procedureNumber: TelemetryKey.OfLong = TelemetryKey.OfLong("onc_rpc.procedure.number")
        public val programName: TelemetryKey.OfString = TelemetryKey.OfString("onc_rpc.program.name")
        public val version: TelemetryKey.OfLong = TelemetryKey.OfLong("onc_rpc.version")
    }
    public object Openai {
        public val apiType: TelemetryKey.OfString = TelemetryKey.OfString("openai.api.type")
        public val requestServiceTier: TelemetryKey.OfString = TelemetryKey.OfString("openai.request.service_tier")
        public val responseServiceTier: TelemetryKey.OfString = TelemetryKey.OfString("openai.response.service_tier")
        public val responseSystemFingerprint: TelemetryKey.OfString = TelemetryKey.OfString("openai.response.system_fingerprint")
    }
    public object Openshift {
        public val clusterquotaName: TelemetryKey.OfString = TelemetryKey.OfString("openshift.clusterquota.name")
        public val clusterquotaUid: TelemetryKey.OfString = TelemetryKey.OfString("openshift.clusterquota.uid")
    }
    public object Opentracing {
        public val refType: TelemetryKey.OfString = TelemetryKey.OfString("opentracing.ref_type")
    }
    public object Oracle {
        public val dbDomain: TelemetryKey.OfString = TelemetryKey.OfString("oracle.db.domain")
        public val dbInstanceName: TelemetryKey.OfString = TelemetryKey.OfString("oracle.db.instance.name")
        public val dbName: TelemetryKey.OfString = TelemetryKey.OfString("oracle.db.name")
        public val dbPdb: TelemetryKey.OfString = TelemetryKey.OfString("oracle.db.pdb")
        public val dbService: TelemetryKey.OfString = TelemetryKey.OfString("oracle.db.service")
    }
    public object OracleCloud {
        public val realm: TelemetryKey.OfString = TelemetryKey.OfString("oracle_cloud.realm")
    }
    public object Os {
        public val buildId: TelemetryKey.OfString = TelemetryKey.OfString("os.build_id")
        public val description: TelemetryKey.OfString = TelemetryKey.OfString("os.description")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("os.name")
        public val type: TelemetryKey.OfString = TelemetryKey.OfString("os.type")
        public val version: TelemetryKey.OfString = TelemetryKey.OfString("os.version")
    }
    public object Otel {
        public val componentName: TelemetryKey.OfString = TelemetryKey.OfString("otel.component.name")
        public val componentType: TelemetryKey.OfString = TelemetryKey.OfString("otel.component.type")
        public val eventName: TelemetryKey.OfString = TelemetryKey.OfString("otel.event.name")
        public val libraryName: TelemetryKey.OfString = TelemetryKey.OfString("otel.library.name")
        public val libraryVersion: TelemetryKey.OfString = TelemetryKey.OfString("otel.library.version")
        public val scopeName: TelemetryKey.OfString = TelemetryKey.OfString("otel.scope.name")
        public val scopeSchemaUrl: TelemetryKey.OfString = TelemetryKey.OfString("otel.scope.schema_url")
        public val scopeVersion: TelemetryKey.OfString = TelemetryKey.OfString("otel.scope.version")
        public val spanParentOrigin: TelemetryKey.OfString = TelemetryKey.OfString("otel.span.parent.origin")
        public val spanSamplingResult: TelemetryKey.OfString = TelemetryKey.OfString("otel.span.sampling_result")
        public val statusCode: TelemetryKey.OfString = TelemetryKey.OfString("otel.status_code")
        public val statusDescription: TelemetryKey.OfString = TelemetryKey.OfString("otel.status_description")
    }
    public object Peer {
        public val service: TelemetryKey.OfString = TelemetryKey.OfString("peer.service")
    }
    public object Pool {
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("pool.name")
    }
    public object Pprof {
        public val locationIsFolded: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("pprof.location.is_folded")
        public val mappingHasFilenames: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("pprof.mapping.has_filenames")
        public val mappingHasFunctions: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("pprof.mapping.has_functions")
        public val mappingHasInlineFrames: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("pprof.mapping.has_inline_frames")
        public val mappingHasLineNumbers: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("pprof.mapping.has_line_numbers")
        public val profileComment: TelemetryKey.OfStringList = TelemetryKey.OfStringList("pprof.profile.comment")
        public val profileDocUrl: TelemetryKey.OfString = TelemetryKey.OfString("pprof.profile.doc_url")
        public val profileDropFrames: TelemetryKey.OfString = TelemetryKey.OfString("pprof.profile.drop_frames")
        public val profileKeepFrames: TelemetryKey.OfString = TelemetryKey.OfString("pprof.profile.keep_frames")
        public val scopeDefaultSampleType: TelemetryKey.OfString = TelemetryKey.OfString("pprof.scope.default_sample_type")
    }
    public object Process {
        public val argsCount: TelemetryKey.OfLong = TelemetryKey.OfLong("process.args_count")
        public val command: TelemetryKey.OfString = TelemetryKey.OfString("process.command")
        public val commandArgs: TelemetryKey.OfStringList = TelemetryKey.OfStringList("process.command_args")
        public val commandLine: TelemetryKey.OfString = TelemetryKey.OfString("process.command_line")
        public val contextSwitchType: TelemetryKey.OfString = TelemetryKey.OfString("process.context_switch_type")
        public val cpuState: TelemetryKey.OfString = TelemetryKey.OfString("process.cpu.state")
        public val creationTime: TelemetryKey.OfString = TelemetryKey.OfString("process.creation.time")
        public val executableBuildIdGnu: TelemetryKey.OfString = TelemetryKey.OfString("process.executable.build_id.gnu")
        public val executableBuildIdGo: TelemetryKey.OfString = TelemetryKey.OfString("process.executable.build_id.go")
        public val executableBuildIdHtlhash: TelemetryKey.OfString = TelemetryKey.OfString("process.executable.build_id.htlhash")
        public val executableBuildIdProfiling: TelemetryKey.OfString = TelemetryKey.OfString("process.executable.build_id.profiling")
        public val executableName: TelemetryKey.OfString = TelemetryKey.OfString("process.executable.name")
        public val executablePath: TelemetryKey.OfString = TelemetryKey.OfString("process.executable.path")
        public val exitCode: TelemetryKey.OfLong = TelemetryKey.OfLong("process.exit.code")
        public val exitTime: TelemetryKey.OfString = TelemetryKey.OfString("process.exit.time")
        public val groupLeaderPid: TelemetryKey.OfLong = TelemetryKey.OfLong("process.group_leader.pid")
        public val interactive: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("process.interactive")
        public val linuxCgroup: TelemetryKey.OfString = TelemetryKey.OfString("process.linux.cgroup")
        public val owner: TelemetryKey.OfString = TelemetryKey.OfString("process.owner")
        public val pagingFaultType: TelemetryKey.OfString = TelemetryKey.OfString("process.paging.fault_type")
        public val parentPid: TelemetryKey.OfLong = TelemetryKey.OfLong("process.parent_pid")
        public val pid: TelemetryKey.OfLong = TelemetryKey.OfLong("process.pid")
        public val realUserId: TelemetryKey.OfLong = TelemetryKey.OfLong("process.real_user.id")
        public val realUserName: TelemetryKey.OfString = TelemetryKey.OfString("process.real_user.name")
        public val runtimeDescription: TelemetryKey.OfString = TelemetryKey.OfString("process.runtime.description")
        public val runtimeName: TelemetryKey.OfString = TelemetryKey.OfString("process.runtime.name")
        public val runtimeVersion: TelemetryKey.OfString = TelemetryKey.OfString("process.runtime.version")
        public val savedUserId: TelemetryKey.OfLong = TelemetryKey.OfLong("process.saved_user.id")
        public val savedUserName: TelemetryKey.OfString = TelemetryKey.OfString("process.saved_user.name")
        public val sessionLeaderPid: TelemetryKey.OfLong = TelemetryKey.OfLong("process.session_leader.pid")
        public val state: TelemetryKey.OfString = TelemetryKey.OfString("process.state")
        public val title: TelemetryKey.OfString = TelemetryKey.OfString("process.title")
        public val userId: TelemetryKey.OfLong = TelemetryKey.OfLong("process.user.id")
        public val userName: TelemetryKey.OfString = TelemetryKey.OfString("process.user.name")
        public val vpid: TelemetryKey.OfLong = TelemetryKey.OfLong("process.vpid")
        public val workingDirectory: TelemetryKey.OfString = TelemetryKey.OfString("process.working_directory")
    }
    public object Profile {
        public val frameType: TelemetryKey.OfString = TelemetryKey.OfString("profile.frame.type")
    }
    public object Rpc {
        public val connectRpcErrorCode: TelemetryKey.OfString = TelemetryKey.OfString("rpc.connect_rpc.error_code")
        public val grpcStatusCode: TelemetryKey.OfString = TelemetryKey.OfString("rpc.grpc.status_code")
        public val jsonrpcErrorCode: TelemetryKey.OfLong = TelemetryKey.OfLong("rpc.jsonrpc.error_code")
        public val jsonrpcErrorMessage: TelemetryKey.OfString = TelemetryKey.OfString("rpc.jsonrpc.error_message")
        public val jsonrpcRequestId: TelemetryKey.OfString = TelemetryKey.OfString("rpc.jsonrpc.request_id")
        public val jsonrpcVersion: TelemetryKey.OfString = TelemetryKey.OfString("rpc.jsonrpc.version")
        public val messageCompressedSize: TelemetryKey.OfLong = TelemetryKey.OfLong("rpc.message.compressed_size")
        public val messageId: TelemetryKey.OfLong = TelemetryKey.OfLong("rpc.message.id")
        public val messageType: TelemetryKey.OfString = TelemetryKey.OfString("rpc.message.type")
        public val messageUncompressedSize: TelemetryKey.OfLong = TelemetryKey.OfLong("rpc.message.uncompressed_size")
        public val method: TelemetryKey.OfString = TelemetryKey.OfString("rpc.method")
        public val methodOriginal: TelemetryKey.OfString = TelemetryKey.OfString("rpc.method_original")
        public val responseStatusCode: TelemetryKey.OfString = TelemetryKey.OfString("rpc.response.status_code")
        public val service: TelemetryKey.OfString = TelemetryKey.OfString("rpc.service")
        public val system: TelemetryKey.OfString = TelemetryKey.OfString("rpc.system")
        public val systemName: TelemetryKey.OfString = TelemetryKey.OfString("rpc.system.name")
    }
    public object SecurityRule {
        public val category: TelemetryKey.OfString = TelemetryKey.OfString("security_rule.category")
        public val description: TelemetryKey.OfString = TelemetryKey.OfString("security_rule.description")
        public val license: TelemetryKey.OfString = TelemetryKey.OfString("security_rule.license")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("security_rule.name")
        public val reference: TelemetryKey.OfString = TelemetryKey.OfString("security_rule.reference")
        public val rulesetName: TelemetryKey.OfString = TelemetryKey.OfString("security_rule.ruleset.name")
        public val uuid: TelemetryKey.OfString = TelemetryKey.OfString("security_rule.uuid")
        public val version: TelemetryKey.OfString = TelemetryKey.OfString("security_rule.version")
    }
    public object Server {
        public val address: TelemetryKey.OfString = TelemetryKey.OfString("server.address")
        public val port: TelemetryKey.OfLong = TelemetryKey.OfLong("server.port")
    }
    public object Service {
        public val criticality: TelemetryKey.OfString = TelemetryKey.OfString("service.criticality")
        public val instanceId: TelemetryKey.OfString = TelemetryKey.OfString("service.instance.id")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("service.name")
        public val namespace: TelemetryKey.OfString = TelemetryKey.OfString("service.namespace")
        public val peerName: TelemetryKey.OfString = TelemetryKey.OfString("service.peer.name")
        public val peerNamespace: TelemetryKey.OfString = TelemetryKey.OfString("service.peer.namespace")
        public val version: TelemetryKey.OfString = TelemetryKey.OfString("service.version")
    }
    public object Session {
        public val id: TelemetryKey.OfString = TelemetryKey.OfString("session.id")
        public val previousId: TelemetryKey.OfString = TelemetryKey.OfString("session.previous_id")
    }
    public object Signalr {
        public val connectionStatus: TelemetryKey.OfString = TelemetryKey.OfString("signalr.connection.status")
        public val transport: TelemetryKey.OfString = TelemetryKey.OfString("signalr.transport")
    }
    public object Source {
        public val address: TelemetryKey.OfString = TelemetryKey.OfString("source.address")
        public val port: TelemetryKey.OfLong = TelemetryKey.OfLong("source.port")
    }
    public val state: TelemetryKey.OfString = TelemetryKey.OfString("state")
    public object System {
        public val cpuLogicalNumber: TelemetryKey.OfLong = TelemetryKey.OfLong("system.cpu.logical_number")
        public val cpuState: TelemetryKey.OfString = TelemetryKey.OfString("system.cpu.state")
        public val device: TelemetryKey.OfString = TelemetryKey.OfString("system.device")
        public val filesystemMode: TelemetryKey.OfString = TelemetryKey.OfString("system.filesystem.mode")
        public val filesystemMountpoint: TelemetryKey.OfString = TelemetryKey.OfString("system.filesystem.mountpoint")
        public val filesystemState: TelemetryKey.OfString = TelemetryKey.OfString("system.filesystem.state")
        public val filesystemType: TelemetryKey.OfString = TelemetryKey.OfString("system.filesystem.type")
        public val memoryLinuxHugepagesState: TelemetryKey.OfString = TelemetryKey.OfString("system.memory.linux.hugepages.state")
        public val memoryLinuxSlabState: TelemetryKey.OfString = TelemetryKey.OfString("system.memory.linux.slab.state")
        public val memoryState: TelemetryKey.OfString = TelemetryKey.OfString("system.memory.state")
        public val networkState: TelemetryKey.OfString = TelemetryKey.OfString("system.network.state")
        public val pagingDirection: TelemetryKey.OfString = TelemetryKey.OfString("system.paging.direction")
        public val pagingFaultType: TelemetryKey.OfString = TelemetryKey.OfString("system.paging.fault.type")
        public val pagingState: TelemetryKey.OfString = TelemetryKey.OfString("system.paging.state")
        public val pagingType: TelemetryKey.OfString = TelemetryKey.OfString("system.paging.type")
        public val processStatus: TelemetryKey.OfString = TelemetryKey.OfString("system.process.status")
        public val processesStatus: TelemetryKey.OfString = TelemetryKey.OfString("system.processes.status")
    }
    public object Telemetry {
        public val distroName: TelemetryKey.OfString = TelemetryKey.OfString("telemetry.distro.name")
        public val distroVersion: TelemetryKey.OfString = TelemetryKey.OfString("telemetry.distro.version")
        public val sdkLanguage: TelemetryKey.OfString = TelemetryKey.OfString("telemetry.sdk.language")
        public val sdkName: TelemetryKey.OfString = TelemetryKey.OfString("telemetry.sdk.name")
        public val sdkVersion: TelemetryKey.OfString = TelemetryKey.OfString("telemetry.sdk.version")
    }
    public object Test {
        public val caseName: TelemetryKey.OfString = TelemetryKey.OfString("test.case.name")
        public val caseResultStatus: TelemetryKey.OfString = TelemetryKey.OfString("test.case.result.status")
        public val suiteName: TelemetryKey.OfString = TelemetryKey.OfString("test.suite.name")
        public val suiteRunStatus: TelemetryKey.OfString = TelemetryKey.OfString("test.suite.run.status")
    }
    public object Thread {
        public val id: TelemetryKey.OfLong = TelemetryKey.OfLong("thread.id")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("thread.name")
    }
    public object Tls {
        public val cipher: TelemetryKey.OfString = TelemetryKey.OfString("tls.cipher")
        public val clientCertificate: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.certificate")
        public val clientCertificateChain: TelemetryKey.OfStringList = TelemetryKey.OfStringList("tls.client.certificate_chain")
        public val clientHashMd5: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.hash.md5")
        public val clientHashSha1: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.hash.sha1")
        public val clientHashSha256: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.hash.sha256")
        public val clientIssuer: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.issuer")
        public val clientJa3: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.ja3")
        public val clientNotAfter: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.not_after")
        public val clientNotBefore: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.not_before")
        public val clientServerName: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.server_name")
        public val clientSubject: TelemetryKey.OfString = TelemetryKey.OfString("tls.client.subject")
        public val clientSupportedCiphers: TelemetryKey.OfStringList = TelemetryKey.OfStringList("tls.client.supported_ciphers")
        public val curve: TelemetryKey.OfString = TelemetryKey.OfString("tls.curve")
        public val established: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("tls.established")
        public val nextProtocol: TelemetryKey.OfString = TelemetryKey.OfString("tls.next_protocol")
        public val protocolName: TelemetryKey.OfString = TelemetryKey.OfString("tls.protocol.name")
        public val protocolVersion: TelemetryKey.OfString = TelemetryKey.OfString("tls.protocol.version")
        public val resumed: TelemetryKey.OfBoolean = TelemetryKey.OfBoolean("tls.resumed")
        public val serverCertificate: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.certificate")
        public val serverCertificateChain: TelemetryKey.OfStringList = TelemetryKey.OfStringList("tls.server.certificate_chain")
        public val serverHashMd5: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.hash.md5")
        public val serverHashSha1: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.hash.sha1")
        public val serverHashSha256: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.hash.sha256")
        public val serverIssuer: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.issuer")
        public val serverJa3s: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.ja3s")
        public val serverNotAfter: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.not_after")
        public val serverNotBefore: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.not_before")
        public val serverSubject: TelemetryKey.OfString = TelemetryKey.OfString("tls.server.subject")
    }
    public object Url {
        public val domain: TelemetryKey.OfString = TelemetryKey.OfString("url.domain")
        public val extension: TelemetryKey.OfString = TelemetryKey.OfString("url.extension")
        public val fragment: TelemetryKey.OfString = TelemetryKey.OfString("url.fragment")
        public val full: TelemetryKey.OfString = TelemetryKey.OfString("url.full")
        public val original: TelemetryKey.OfString = TelemetryKey.OfString("url.original")
        public val path: TelemetryKey.OfString = TelemetryKey.OfString("url.path")
        public val port: TelemetryKey.OfLong = TelemetryKey.OfLong("url.port")
        public val query: TelemetryKey.OfString = TelemetryKey.OfString("url.query")
        public val registeredDomain: TelemetryKey.OfString = TelemetryKey.OfString("url.registered_domain")
        public val scheme: TelemetryKey.OfString = TelemetryKey.OfString("url.scheme")
        public val subdomain: TelemetryKey.OfString = TelemetryKey.OfString("url.subdomain")
        public val template: TelemetryKey.OfString = TelemetryKey.OfString("url.template")
        public val topLevelDomain: TelemetryKey.OfString = TelemetryKey.OfString("url.top_level_domain")
    }
    public object User {
        public val email: TelemetryKey.OfString = TelemetryKey.OfString("user.email")
        public val fullName: TelemetryKey.OfString = TelemetryKey.OfString("user.full_name")
        public val hash: TelemetryKey.OfString = TelemetryKey.OfString("user.hash")
        public val id: TelemetryKey.OfString = TelemetryKey.OfString("user.id")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("user.name")
        public val roles: TelemetryKey.OfStringList = TelemetryKey.OfStringList("user.roles")
    }
    public object UserAgent {
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("user_agent.name")
        public val original: TelemetryKey.OfString = TelemetryKey.OfString("user_agent.original")
        public val osName: TelemetryKey.OfString = TelemetryKey.OfString("user_agent.os.name")
        public val osVersion: TelemetryKey.OfString = TelemetryKey.OfString("user_agent.os.version")
        public val syntheticType: TelemetryKey.OfString = TelemetryKey.OfString("user_agent.synthetic.type")
        public val version: TelemetryKey.OfString = TelemetryKey.OfString("user_agent.version")
    }
    public object V8js {
        public val gcType: TelemetryKey.OfString = TelemetryKey.OfString("v8js.gc.type")
        public val heapSpaceName: TelemetryKey.OfString = TelemetryKey.OfString("v8js.heap.space.name")
        public val resourceType: TelemetryKey.OfString = TelemetryKey.OfString("v8js.resource.type")
    }
    public object Vcs {
        public val changeId: TelemetryKey.OfString = TelemetryKey.OfString("vcs.change.id")
        public val changeState: TelemetryKey.OfString = TelemetryKey.OfString("vcs.change.state")
        public val changeTitle: TelemetryKey.OfString = TelemetryKey.OfString("vcs.change.title")
        public val lineChangeType: TelemetryKey.OfString = TelemetryKey.OfString("vcs.line_change.type")
        public val ownerName: TelemetryKey.OfString = TelemetryKey.OfString("vcs.owner.name")
        public val providerName: TelemetryKey.OfString = TelemetryKey.OfString("vcs.provider.name")
        public val refBaseName: TelemetryKey.OfString = TelemetryKey.OfString("vcs.ref.base.name")
        public val refBaseRevision: TelemetryKey.OfString = TelemetryKey.OfString("vcs.ref.base.revision")
        public val refBaseType: TelemetryKey.OfString = TelemetryKey.OfString("vcs.ref.base.type")
        public val refHeadName: TelemetryKey.OfString = TelemetryKey.OfString("vcs.ref.head.name")
        public val refHeadRevision: TelemetryKey.OfString = TelemetryKey.OfString("vcs.ref.head.revision")
        public val refHeadType: TelemetryKey.OfString = TelemetryKey.OfString("vcs.ref.head.type")
        public val refType: TelemetryKey.OfString = TelemetryKey.OfString("vcs.ref.type")
        public val repositoryChangeId: TelemetryKey.OfString = TelemetryKey.OfString("vcs.repository.change.id")
        public val repositoryChangeTitle: TelemetryKey.OfString = TelemetryKey.OfString("vcs.repository.change.title")
        public val repositoryName: TelemetryKey.OfString = TelemetryKey.OfString("vcs.repository.name")
        public val repositoryRefName: TelemetryKey.OfString = TelemetryKey.OfString("vcs.repository.ref.name")
        public val repositoryRefRevision: TelemetryKey.OfString = TelemetryKey.OfString("vcs.repository.ref.revision")
        public val repositoryRefType: TelemetryKey.OfString = TelemetryKey.OfString("vcs.repository.ref.type")
        public val repositoryUrlFull: TelemetryKey.OfString = TelemetryKey.OfString("vcs.repository.url.full")
        public val revisionDeltaDirection: TelemetryKey.OfString = TelemetryKey.OfString("vcs.revision_delta.direction")
    }
    public object Webengine {
        public val description: TelemetryKey.OfString = TelemetryKey.OfString("webengine.description")
        public val name: TelemetryKey.OfString = TelemetryKey.OfString("webengine.name")
        public val version: TelemetryKey.OfString = TelemetryKey.OfString("webengine.version")
    }
    public object Zos {
        public val smfId: TelemetryKey.OfString = TelemetryKey.OfString("zos.smf.id")
        public val sysplexName: TelemetryKey.OfString = TelemetryKey.OfString("zos.sysplex.name")
    }
}