package com.lightningkite.services.database.test

import com.lightningkite.services.database.*
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.time.Instant

abstract class ModificationTests() {
    abstract val database: Database

    @Test
    fun test_orderedOneMods() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("test_orderedOneMods"))
        val max = 10
        collection.insert((1..max).map { LargeTestModel(int = it, long = it.toLong()) })
        assertEquals(collection.count(), max)
        val updated = collection.updateOne(
            condition = Condition.Always,
            modification = modification { it.boolean assign true },
            orderBy = sort { it.int.descending() }
        )
        assertEquals(max, updated.new!!.int)
        val deleted = collection.deleteOne(
            condition = Condition.Always,
            orderBy = sort { it.int.descending() }
        )
        assertEquals(max, deleted!!.int)
        assertEquals(collection.count(), max - 1)
    }

    @Test
    fun test_orderedOneModsIgnoringResult() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("test_orderedOneModsIgnoringResult"))
        val max = 10
        collection.insert((1..max).map { LargeTestModel(int = it, long = it.toLong()) })

        assertEquals(true, collection.updateOneIgnoringResult(
            condition = Condition.Always,
            modification = modification { it.boolean assign true },
            orderBy = sort { it.int.descending() }
        ))
        // Exactly one row, and it must be the one the sort selected.
        assertEquals(listOf(max), collection.find(condition { it.boolean eq true }).toList().map { it.int })

        assertEquals(true, collection.deleteOneIgnoringOld(
            condition = Condition.Always,
            orderBy = sort { it.int.descending() }
        ))
        assertEquals(max - 1, collection.count())
        assertEquals(null, collection.findOne(condition { it.int eq max }))
    }

    @Test
    fun test_chainFull() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_chainFull"))
        val item = LargeTestModel(boolean = false)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> {
            it assign item.copy(boolean = true)
            it.boolean assign true
        }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(true, result.boolean)
        assertEquals(modification(item), result)
    }

    // region autogenerated modifications
    @Test
    fun test_Boolean_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Boolean_set"))
        val item = LargeTestModel(boolean = false)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.boolean assign true }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(true, result.boolean)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Boolean_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Boolean_set_nullable"))
        val item = LargeTestModel(booleanNullable = false)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.booleanNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.booleanNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Boolean_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Boolean_set_nullable2"))
        val item = LargeTestModel(booleanNullable = false)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.booleanNullable assign true }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(true, result.booleanNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_set"))
        val item = LargeTestModel(list = listOf(4, 5, 6))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.list assign listOf(7, 8, 9) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(7, 8, 9), result.list)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_set_nullable"))
        val item = LargeTestModel(listNullable = listOf(4, 5, 6))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.listNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.listNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_set_nullable2"))
        val item = LargeTestModel(listNullable = listOf(4, 5, 6))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.listNullable assign listOf(7, 8, 9) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(7, 8, 9), result.listNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Map_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Map_set"))
        val item = LargeTestModel(map = mapOf("b" to 2))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.map assign mapOf("c" to 3) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(mapOf("c" to 3), result.map)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Map_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Map_set_nullable"))
        val item = LargeTestModel(mapNullable = mapOf("b" to 2))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.mapNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.mapNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Map_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Map_set_nullable2"))
        val item = LargeTestModel(mapNullable = mapOf("b" to 2))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.mapNullable assign mapOf("c" to 3) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(mapOf("c" to 3), result.mapNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_set"))
        val item = LargeTestModel(byte = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byte assign 3.toByte() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.toByte(), result.byte)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_set_nullable"))
        val item = LargeTestModel(byteNullable = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byteNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.byteNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_set_nullable2"))
        val item = LargeTestModel(byteNullable = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byteNullable assign 3.toByte() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.toByte(), result.byteNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_set"))
        val item = LargeTestModel(short = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.short assign 3.toShort() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.toShort(), result.short)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_set_nullable"))
        val item = LargeTestModel(shortNullable = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.shortNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.shortNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_set_nullable2"))
        val item = LargeTestModel(shortNullable = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.shortNullable assign 3.toShort() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.toShort(), result.shortNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_set"))
        val item = LargeTestModel(int = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.int assign 3 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3, result.int)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_set_nullable"))
        val item = LargeTestModel(intNullable = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.intNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.intNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_set_nullable2"))
        val item = LargeTestModel(intNullable = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.intNullable assign 3 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3, result.intNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_set"))
        val item = LargeTestModel(long = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.long assign 3L }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3L, result.long)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_set_nullable"))
        val item = LargeTestModel(longNullable = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.longNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.longNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_set_nullable2"))
        val item = LargeTestModel(longNullable = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.longNullable assign 3L }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3L, result.longNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_set"))
        val item = LargeTestModel(float = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.float assign 3f }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3f, result.float)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_set_nullable"))
        val item = LargeTestModel(floatNullable = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.floatNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.floatNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_set_nullable2"))
        val item = LargeTestModel(floatNullable = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.floatNullable assign 3f }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3f, result.floatNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_set"))
        val item = LargeTestModel(double = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.double assign 3.0 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.0, result.double)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_set_nullable"))
        val item = LargeTestModel(doubleNullable = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.doubleNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.doubleNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_set_nullable2"))
        val item = LargeTestModel(doubleNullable = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.doubleNullable assign 3.0 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.0, result.doubleNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_String_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_String_set"))
        val item = LargeTestModel(string = "aba")
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.string assign "aca" }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals("aca", result.string)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_String_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_String_set_nullable"))
        val item = LargeTestModel(stringNullable = "aba")
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.stringNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.stringNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_String_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_String_set_nullable2"))
        val item = LargeTestModel(stringNullable = "aba")
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.stringNullable assign "aca" }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals("aca", result.stringNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Instant_set() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Instant_set"))
        val item = LargeTestModel(instant = Instant.fromEpochMilliseconds(10000L))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.instant assign Instant.fromEpochMilliseconds(15000L) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(Instant.fromEpochMilliseconds(15000L), result.instant)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Instant_set_nullable() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Instant_set_nullable"))
        val item = LargeTestModel(instantNullable = Instant.fromEpochMilliseconds(10000L))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.instantNullable assign null }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(null, result.instantNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Instant_set_nullable2() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Instant_set_nullable2"))
        val item = LargeTestModel(instantNullable = Instant.fromEpochMilliseconds(10000L))
        collection.insertOne(item)
        val modification =
            modification<LargeTestModel> { it.instantNullable assign Instant.fromEpochMilliseconds(15000L) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(Instant.fromEpochMilliseconds(15000L), result.instantNullable)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_coerceAtMost() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_coerceAtMost"))
        val item = LargeTestModel(byte = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byte coerceAtMost 1.toByte() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(1.toByte(), result.byte)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_coerceAtMost_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_coerceAtMost_miss"))
        val item = LargeTestModel(byte = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byte coerceAtMost 3.toByte() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2.toByte(), result.byte)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_coerceAtLeast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_coerceAtLeast"))
        val item = LargeTestModel(byte = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byte coerceAtLeast 3.toByte() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.toByte(), result.byte)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_coerceAtLeast_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_coerceAtLeast_miss"))
        val item = LargeTestModel(byte = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byte coerceAtLeast 1.toByte() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2.toByte(), result.byte)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_coerceAtMost() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_coerceAtMost"))
        val item = LargeTestModel(short = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.short coerceAtMost 1.toShort() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(1.toShort(), result.short)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_coerceAtMost_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_coerceAtMost_miss"))
        val item = LargeTestModel(short = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.short coerceAtMost 3.toShort() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2.toShort(), result.short)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_coerceAtLeast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_coerceAtLeast"))
        val item = LargeTestModel(short = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.short coerceAtLeast 3.toShort() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.toShort(), result.short)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_coerceAtLeast_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_coerceAtLeast_miss"))
        val item = LargeTestModel(short = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.short coerceAtLeast 1.toShort() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2.toShort(), result.short)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_coerceAtMost() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_coerceAtMost"))
        val item = LargeTestModel(int = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.int coerceAtMost 1 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(1, result.int)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_coerceAtMost_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_coerceAtMost_miss"))
        val item = LargeTestModel(int = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.int coerceAtMost 3 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2, result.int)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_coerceAtLeast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_coerceAtLeast"))
        val item = LargeTestModel(int = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.int coerceAtLeast 3 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3, result.int)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_coerceAtLeast_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_coerceAtLeast_miss"))
        val item = LargeTestModel(int = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.int coerceAtLeast 1 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2, result.int)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_coerceAtMost() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_coerceAtMost"))
        val item = LargeTestModel(long = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.long coerceAtMost 1L }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(1L, result.long)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_coerceAtMost_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_coerceAtMost_miss"))
        val item = LargeTestModel(long = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.long coerceAtMost 3L }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2L, result.long)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_coerceAtLeast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_coerceAtLeast"))
        val item = LargeTestModel(long = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.long coerceAtLeast 3L }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3L, result.long)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_coerceAtLeast_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_coerceAtLeast_miss"))
        val item = LargeTestModel(long = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.long coerceAtLeast 1L }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2L, result.long)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_coerceAtMost() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_coerceAtMost"))
        val item = LargeTestModel(float = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.float coerceAtMost 1f }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(1f, result.float)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_coerceAtMost_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_coerceAtMost_miss"))
        val item = LargeTestModel(float = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.float coerceAtMost 3f }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2f, result.float)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_coerceAtLeast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_coerceAtLeast"))
        val item = LargeTestModel(float = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.float coerceAtLeast 3f }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3f, result.float)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_coerceAtLeast_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_coerceAtLeast_miss"))
        val item = LargeTestModel(float = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.float coerceAtLeast 1f }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2f, result.float)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_coerceAtMost() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_coerceAtMost"))
        val item = LargeTestModel(double = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.double coerceAtMost 1.0 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(1.0, result.double)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_coerceAtMost_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_coerceAtMost_miss"))
        val item = LargeTestModel(double = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.double coerceAtMost 3.0 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2.0, result.double)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_coerceAtLeast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_coerceAtLeast"))
        val item = LargeTestModel(double = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.double coerceAtLeast 3.0 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(3.0, result.double)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_coerceAtLeast_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_coerceAtLeast_miss"))
        val item = LargeTestModel(double = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.double coerceAtLeast 1.0 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(2.0, result.double)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_String_coerceAtMost() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_String_coerceAtMost"))
        val item = LargeTestModel(string = "aba")
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.string coerceAtMost "aaa" }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals("aaa", result.string)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_String_coerceAtMost_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_String_coerceAtMost_miss"))
        val item = LargeTestModel(string = "aba")
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.string coerceAtMost "aca" }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals("aba", result.string)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_String_coerceAtLeast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_String_coerceAtLeast"))
        val item = LargeTestModel(string = "aba")
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.string coerceAtLeast "aca" }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals("aca", result.string)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_String_coerceAtLeast_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_String_coerceAtLeast_miss"))
        val item = LargeTestModel(string = "aba")
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.string coerceAtLeast "aaa" }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals("aba", result.string)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Instant_coerceAtMost() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Instant_coerceAtMost"))
        val item = LargeTestModel(instant = Instant.fromEpochMilliseconds(10000L))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.instant coerceAtMost Instant.fromEpochMilliseconds(5000L) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(Instant.fromEpochMilliseconds(5000L), result.instant)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Instant_coerceAtMost_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Instant_coerceAtMost_miss"))
        val item = LargeTestModel(instant = Instant.fromEpochMilliseconds(10000L))
        collection.insertOne(item)
        val modification =
            modification<LargeTestModel> { it.instant coerceAtMost Instant.fromEpochMilliseconds(15000L) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(Instant.fromEpochMilliseconds(10000L), result.instant)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Instant_coerceAtLeast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Instant_coerceAtLeast"))
        val item = LargeTestModel(instant = Instant.fromEpochMilliseconds(10000L))
        collection.insertOne(item)
        val modification =
            modification<LargeTestModel> { it.instant coerceAtLeast Instant.fromEpochMilliseconds(15000L) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(Instant.fromEpochMilliseconds(15000L), result.instant)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Instant_coerceAtLeast_miss() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Instant_coerceAtLeast_miss"))
        val item = LargeTestModel(instant = Instant.fromEpochMilliseconds(10000L))
        collection.insertOne(item)
        val modification =
            modification<LargeTestModel> { it.instant coerceAtLeast Instant.fromEpochMilliseconds(5000L) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(Instant.fromEpochMilliseconds(10000L), result.instant)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_inc() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_inc"))
        val item = LargeTestModel(byte = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byte += 3.toByte() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3.toByte() + 2.toByte()).toByte(), result.byte)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Byte_mul() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Byte_mul"))
        val item = LargeTestModel(byte = 2.toByte())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.byte *= 3.toByte() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3.toByte() * 2.toByte()).toByte(), result.byte)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_inc() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_inc"))
        val item = LargeTestModel(short = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.short += 3.toShort() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3.toShort() + 2.toShort()).toShort(), result.short)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Short_mul() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Short_mul"))
        val item = LargeTestModel(short = 2.toShort())
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.short *= 3.toShort() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3.toShort() * 2.toShort()).toShort(), result.short)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_inc() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_inc"))
        val item = LargeTestModel(int = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.int += 3 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3 + 2), result.int)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Int_mul() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Int_mul"))
        val item = LargeTestModel(int = 2)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.int *= 3 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3 * 2), result.int)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_inc() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_inc"))
        val item = LargeTestModel(long = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.long += 3L }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3L + 2L), result.long)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Long_mul() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Long_mul"))
        val item = LargeTestModel(long = 2L)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.long *= 3L }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3L * 2L), result.long)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_inc() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_inc"))
        val item = LargeTestModel(float = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.float += 3f }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3f + 2f), result.float)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Float_mul() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Float_mul"))
        val item = LargeTestModel(float = 2f)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.float *= 3f }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3f * 2f), result.float)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_inc() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_inc"))
        val item = LargeTestModel(double = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.double += 3.0 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3.0 + 2.0), result.double)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Double_mul() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Double_mul"))
        val item = LargeTestModel(double = 2.0)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.double *= 3.0 }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals((3.0 * 2.0), result.double)
        assertEquals(modification(item), result)
    }

    // endregion autogenerated modifications

    @Test
    fun test_List_push() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_push"))
        val item = LargeTestModel(list = listOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.list.addAll(listOf(3, 4, 5)) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(1, 2, 3, 3, 4, 5), result.list)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_pull() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_pull"))
        val item = LargeTestModel(list = listOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.list.removeAll { it gt 1 } }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(1), result.list)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_pull_embedded() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("test_List_pull_embedded"))
        val item =
            LargeTestModel(listEmbedded = listOf(ClassUsedForEmbedding(value2 = 1), ClassUsedForEmbedding(value2 = 2)))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.listEmbedded.removeAll { it.value2 gt 1 } }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(ClassUsedForEmbedding(value2 = 1)), result.listEmbedded)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_pullAll() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_pullAll"))
        val item = LargeTestModel(list = listOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.list.removeAll(listOf(2, 3)) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(1), result.list)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_popFirst() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_popFirst"))
        val item = LargeTestModel(list = listOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.list.dropFirst() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(2, 3), result.list)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_popLast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_popLast"))
        val item = LargeTestModel(list = listOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.list.dropLast() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(1, 2), result.list)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_List_matching() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_List_matching"))
        val item = LargeTestModel(list = listOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.list.forEachIf({ it gt 2 }, { it *= 2 }) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(listOf(1, 2, 6), result.list)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Set_push() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Set_push"))
        val item = LargeTestModel(set = setOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.set.addAll(setOf(3, 4, 5)) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(setOf(1, 2, 3, 3, 4, 5), result.set)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Set_pull() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Set_pull"))
        val item = LargeTestModel(set = setOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.set.removeAll { it gt 1 } }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(setOf(1), result.set)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Set_pull_embedded() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("test_Set_pull_embedded"))
        val item =
            LargeTestModel(setEmbedded = setOf(ClassUsedForEmbedding(value2 = 1), ClassUsedForEmbedding(value2 = 2)))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.setEmbedded.removeAll { it.value2 gt 1 } }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(setOf(ClassUsedForEmbedding(value2 = 1)), result.setEmbedded)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Set_pullAll() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Set_pullAll"))
        val item = LargeTestModel(set = setOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.set.removeAll(setOf(2, 3)) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(setOf(1), result.set)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Set_popFirst() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Set_popFirst"))
        val item = LargeTestModel(set = setOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.set.dropFirst() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(setOf(2, 3), result.set)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Set_popLast() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Set_popLast"))
        val item = LargeTestModel(set = setOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.set.dropLast() }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(setOf(1, 2), result.set)
        assertEquals(modification(item), result)
    }

    @Test
    fun test_Set_matching() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Set_matching"))
        val item = LargeTestModel(set = setOf(1, 2, 3))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.set.forEachIf({ it gt 2 }, { it *= 2 }) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(setOf(1, 2, 6), result.set)
        assertEquals(modification(item), result)
    }

    @Test
    open fun test_Map_setField() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Map_setField"))
        val item = LargeTestModel(map = mapOf("a" to 1))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.map += mapOf("b" to 2) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(mapOf("a" to 1, "b" to 2), result.map)
        assertEquals(modification(item), result)
    }

    @Test
    open fun test_Map_unsetField() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_Map_setField"))
        val item = LargeTestModel(map = mapOf("a" to 1, "b" to 2))
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.map.removeKeys(setOf("a")) }
        collection.updateOneById(item._id, modification)
        val result = collection.get(item._id)!!
        assertEquals(mapOf("b" to 2), result.map)
        assertEquals(modification(item), result)
    }

    // region notNull
    // A `notNull` modification must leave a null value alone on every backend, exactly as it does in memory.
    // Guards that predict the stored result with `modification(old)` rely on this.

    private suspend fun notNullTest(name: String, items: List<LargeTestModel>, modification: Modification<LargeTestModel>) {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_$name"))
        collection.insert(items)
        for (item in items) {
            val change = collection.updateOneById(item._id, modification)
            val stored = collection.get(item._id)
            assertEquals(modification(item), stored)
            // MongoDB reports a row failing the check as unmatched; see test_notNull_unchangedRowsStillMatch.
            if (change.old != null) assertEquals(stored, change.new)
        }
    }

    @Test
    fun test_notNull_field_assign() = runTest {
        notNullTest(
            "test_notNull_field_assign",
            listOf(LargeTestModel(embeddedNullable = null), LargeTestModel(embeddedNullable = ClassUsedForEmbedding("a", 2))),
            modification { it.embeddedNullable.notNull.value1 assign "changed" }
        )
    }

    @Test
    fun test_notNull_assign() = runTest {
        notNullTest(
            "test_notNull_assign",
            listOf(LargeTestModel(embeddedNullable = null), LargeTestModel(embeddedNullable = ClassUsedForEmbedding("a", 2))),
            modification { it.embeddedNullable.notNull assign ClassUsedForEmbedding("forged", 9) }
        )
    }

    @Test
    fun test_notNull_increment() = runTest {
        notNullTest(
            "test_notNull_increment",
            listOf(LargeTestModel(intNullable = null), LargeTestModel(intNullable = 5)),
            modification { it.intNullable.notNull += 1 }
        )
    }

    @Test
    fun test_notNull_listAppend() = runTest {
        notNullTest(
            "test_notNull_listAppend",
            listOf(LargeTestModel(listNullable = null), LargeTestModel(listNullable = listOf(1))),
            modification { it.listNullable.notNull += listOf(2, 3) }
        )
    }

    @Test
    open fun test_notNull_chain() = runTest {
        notNullTest(
            "test_notNull_chain",
            listOf(
                LargeTestModel(embeddedNullable = null, intNullable = null),
                LargeTestModel(embeddedNullable = ClassUsedForEmbedding("a", 2), intNullable = 5),
            ),
            modification {
                it.int assign 7
                it.embeddedNullable.notNull.value1 assign "changed"
                it.embeddedNullable.notNull.value2 += 1
                it.intNullable.notNull coerceAtMost 3
            }
        )
    }

    @Test
    fun test_notNull_updateMany() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_notNull_updateMany"))
        val items = listOf(LargeTestModel(intNullable = null), LargeTestModel(intNullable = 5))
        collection.insert(items)
        val modification = modification<LargeTestModel> { it.intNullable.notNull += 1 }
        val changes = collection.updateMany(Condition.Always, modification)
        val expected = items.map { modification(it) }.sortedBy { it._id }
        assertEquals(expected, collection.find(Condition.Always).toList().sortedBy { it._id })
        // MongoDB leaves out the row failing the check; see test_notNull_unchangedRowsStillMatch.
        for (change in changes.changes) assertEquals(modification(change.old!!), change.new)
        assertTrue(changes.changes.any { it.old!!.intNullable != null })
    }

    @Test
    fun test_notNull_updateManyIgnoringResult() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_notNull_updateManyIgnoringResult"))
        val items = listOf(
            LargeTestModel(embeddedNullable = null, intNullable = null),
            LargeTestModel(embeddedNullable = ClassUsedForEmbedding("a", 2), intNullable = 5),
        )
        collection.insert(items)
        val modification = modification<LargeTestModel> {
            it.embeddedNullable.notNull.value1 assign "changed"
            it.intNullable.notNull coerceAtMost 3
        }
        collection.updateManyIgnoringResult(Condition.Always, modification)
        assertEquals(items.map { modification(it) }.sortedBy { it._id }, collection.find(Condition.Always).toList().sortedBy { it._id })
    }

    @Test
    fun test_notNull_upsertOne_existing() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_notNull_upsertOne_existing"))
        val item = LargeTestModel(intNullable = null)
        collection.insertOne(item)
        val modification = modification<LargeTestModel> { it.intNullable.notNull += 1 }
        collection.upsertOne(condition { it._id eq item._id }, modification, item)
        assertEquals(item, collection.get(item._id))
    }

    // The check sees the value after the earlier parts of the same modification, not the stored one.
    @Test
    fun test_notNull_afterAssign() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<NullableIntTestModel>("NullableIntTestModel_test_notNull_afterAssign"))
        val item = NullableIntTestModel(value = null)
        collection.insertOne(item)
        val modification = modification<NullableIntTestModel> {
            it.value assign 3
            it.value.notNull += 1
        }
        val change = collection.updateOneById(item._id, modification)
        val stored = collection.get(item._id)
        assertEquals(modification(item), stored)
        assertEquals(stored, change.new)
    }

    // MongoDB compares an array with null element by element, so the null check mustn't reject [null].
    @Test
    fun test_notNull_listWithNullElements_append() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<NullableIntsTestModel>("NullableIntsTestModel_test_notNull_listWithNullElements_append"))
        val items = listOf(null, listOf(null), listOf(1)).map { NullableIntsTestModel(intsNullable = it) }
        collection.insert(items)
        val modification = modification<NullableIntsTestModel> { it.intsNullable.notNull += listOf(3) }
        for (item in items) {
            val change = collection.updateOneById(item._id, modification)
            val stored = collection.get(item._id)
            assertEquals(modification(item), stored)
            if (change.old != null) assertEquals(stored, change.new)
        }
    }

    @Test
    open fun test_notNull_forEach() = runTest {
        notNullTest(
            "test_notNull_forEach",
            listOf(LargeTestModel(listNullable = null), LargeTestModel(listNullable = listOf(1, 2))),
            modification { it.listNullable.notNull.forEach { it += 1 } }
        )
    }

    // A row whose value fails the check still matches; it's just left unchanged.
    @Test
    open fun test_notNull_unchangedRowsStillMatch() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<LargeTestModel>("LargeTestModel_test_notNull_unchangedRowsStillMatch"))
        val item = LargeTestModel(intNullable = null)
        collection.insert(listOf(item, LargeTestModel(intNullable = 5)))
        val modification = modification<LargeTestModel> { it.intNullable.notNull += 1 }
        val byId = condition<LargeTestModel> { it._id eq item._id }

        assertEquals(EntryChange(item, item), collection.updateOne(byId, modification))
        assertTrue(collection.updateOneIgnoringResult(byId, modification))
        assertEquals(2, collection.updateManyIgnoringResult(Condition.Always, modification))
        assertEquals(EntryChange(item, item), collection.upsertOne(byId, modification, item))
        assertTrue(collection.upsertOneIgnoringResult(byId, modification, item))
        assertEquals(item, collection.get(item._id))
        assertEquals(2, collection.count(Condition.Always))
    }

    @Test
    open fun test_notNull_inList() = runTest {
        val collection = database.prepare(DatabaseTableDefinition<NullableInListTestModel>("NullableInListTestModel_test_notNull_inList"))
        val item = NullableInListTestModel(
            items = listOf(
                EmbeddedNullable(name = "a", embed1 = null),
                EmbeddedNullable(name = "a", embed1 = ClassUsedForEmbedding("x", 1)),
                EmbeddedNullable(name = "b", embed1 = ClassUsedForEmbedding("y", 2)),
            )
        )
        collection.insertOne(item)
        val modification = modification<NullableInListTestModel> {
            it.items.forEach { it.embed1.notNull.value2 += 1 }
            it.items.forEachIf(
                condition = { it.name eq "a" },
                modification = {
                    it.name assign "changed"
                    it.embed1.notNull.value1 assign "changed"
                }
            )
        }
        collection.updateOneById(item._id, modification)
        assertEquals(modification(item), collection.get(item._id))
    }

    // endregion

    @Test
    fun san() {
        val before = LargeTestModel(stringNullable = "true")
        val after = modification<LargeTestModel> { it.stringNullable assign null }(before)
        println(before.stringNullable)
        println(after.stringNullable)
    }
}