package com.lightningkite.services

public object MetricKeys {
    public object Android {
        public val appState: MetricKey.OfString = MetricKey.OfString("android.app.state")
        public val osApiLevel: MetricKey.OfString = MetricKey.OfString("android.os.api_level")
        public val state: MetricKey.OfString = MetricKey.OfString("android.state")
    }
    public object App {
        public val buildId: MetricKey.OfString = MetricKey.OfString("app.build_id")
        public val crashId: MetricKey.OfString = MetricKey.OfString("app.crash.id")
        public val installationId: MetricKey.OfString = MetricKey.OfString("app.installation.id")
        public val jankFrameCount: MetricKey.OfLong = MetricKey.OfLong("app.jank.frame_count")
        public val jankPeriod: MetricKey.OfDouble = MetricKey.OfDouble("app.jank.period")
        public val jankThreshold: MetricKey.OfDouble = MetricKey.OfDouble("app.jank.threshold")
        public val screenCoordinateX: MetricKey.OfLong = MetricKey.OfLong("app.screen.coordinate.x")
        public val screenCoordinateY: MetricKey.OfLong = MetricKey.OfLong("app.screen.coordinate.y")
        public val screenId: MetricKey.OfString = MetricKey.OfString("app.screen.id")
        public val screenName: MetricKey.OfString = MetricKey.OfString("app.screen.name")
        public val widgetId: MetricKey.OfString = MetricKey.OfString("app.widget.id")
        public val widgetName: MetricKey.OfString = MetricKey.OfString("app.widget.name")
    }
    public object Artifact {
        public val attestationFilename: MetricKey.OfString = MetricKey.OfString("artifact.attestation.filename")
        public val attestationHash: MetricKey.OfString = MetricKey.OfString("artifact.attestation.hash")
        public val attestationId: MetricKey.OfString = MetricKey.OfString("artifact.attestation.id")
        public val filename: MetricKey.OfString = MetricKey.OfString("artifact.filename")
        public val hash: MetricKey.OfString = MetricKey.OfString("artifact.hash")
        public val purl: MetricKey.OfString = MetricKey.OfString("artifact.purl")
        public val version: MetricKey.OfString = MetricKey.OfString("artifact.version")
    }
    public object Aspnetcore {
        public val authenticationResult: MetricKey.OfString = MetricKey.OfString("aspnetcore.authentication.result")
        public val authenticationScheme: MetricKey.OfString = MetricKey.OfString("aspnetcore.authentication.scheme")
        public val authorizationPolicy: MetricKey.OfString = MetricKey.OfString("aspnetcore.authorization.policy")
        public val authorizationResult: MetricKey.OfString = MetricKey.OfString("aspnetcore.authorization.result")
        public val diagnosticsExceptionResult: MetricKey.OfString = MetricKey.OfString("aspnetcore.diagnostics.exception.result")
        public val diagnosticsHandlerType: MetricKey.OfString = MetricKey.OfString("aspnetcore.diagnostics.handler.type")
        public val identityErrorCode: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.error_code")
        public val identityPasswordCheckResult: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.password_check_result")
        public val identityResult: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.result")
        public val identitySignInResult: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.sign_in.result")
        public val identitySignInType: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.sign_in.type")
        public val identityTokenPurpose: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.token_purpose")
        public val identityTokenVerified: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.token_verified")
        public val identityUserUpdateType: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.user.update_type")
        public val identityUserType: MetricKey.OfString = MetricKey.OfString("aspnetcore.identity.user_type")
        public val memoryPoolOwner: MetricKey.OfString = MetricKey.OfString("aspnetcore.memory_pool.owner")
        public val rateLimitingPolicy: MetricKey.OfString = MetricKey.OfString("aspnetcore.rate_limiting.policy")
        public val rateLimitingResult: MetricKey.OfString = MetricKey.OfString("aspnetcore.rate_limiting.result")
        public val requestIsUnhandled: MetricKey.OfBoolean = MetricKey.OfBoolean("aspnetcore.request.is_unhandled")
        public val routingIsFallback: MetricKey.OfBoolean = MetricKey.OfBoolean("aspnetcore.routing.is_fallback")
        public val routingMatchStatus: MetricKey.OfString = MetricKey.OfString("aspnetcore.routing.match_status")
        public val signInIsPersistent: MetricKey.OfBoolean = MetricKey.OfBoolean("aspnetcore.sign_in.is_persistent")
        public val userIsAuthenticated: MetricKey.OfBoolean = MetricKey.OfBoolean("aspnetcore.user.is_authenticated")
    }
    public object Aws {
        public val bedrockGuardrailId: MetricKey.OfString = MetricKey.OfString("aws.bedrock.guardrail.id")
        public val bedrockKnowledgeBaseId: MetricKey.OfString = MetricKey.OfString("aws.bedrock.knowledge_base.id")
        public val dynamodbAttributeDefinitions: MetricKey.OfStringList = MetricKey.OfStringList("aws.dynamodb.attribute_definitions")
        public val dynamodbAttributesToGet: MetricKey.OfStringList = MetricKey.OfStringList("aws.dynamodb.attributes_to_get")
        public val dynamodbConsistentRead: MetricKey.OfBoolean = MetricKey.OfBoolean("aws.dynamodb.consistent_read")
        public val dynamodbConsumedCapacity: MetricKey.OfStringList = MetricKey.OfStringList("aws.dynamodb.consumed_capacity")
        public val dynamodbCount: MetricKey.OfLong = MetricKey.OfLong("aws.dynamodb.count")
        public val dynamodbExclusiveStartTable: MetricKey.OfString = MetricKey.OfString("aws.dynamodb.exclusive_start_table")
        public val dynamodbGlobalSecondaryIndexUpdates: MetricKey.OfStringList = MetricKey.OfStringList("aws.dynamodb.global_secondary_index_updates")
        public val dynamodbGlobalSecondaryIndexes: MetricKey.OfStringList = MetricKey.OfStringList("aws.dynamodb.global_secondary_indexes")
        public val dynamodbIndexName: MetricKey.OfString = MetricKey.OfString("aws.dynamodb.index_name")
        public val dynamodbItemCollectionMetrics: MetricKey.OfString = MetricKey.OfString("aws.dynamodb.item_collection_metrics")
        public val dynamodbLimit: MetricKey.OfLong = MetricKey.OfLong("aws.dynamodb.limit")
        public val dynamodbLocalSecondaryIndexes: MetricKey.OfStringList = MetricKey.OfStringList("aws.dynamodb.local_secondary_indexes")
        public val dynamodbProjection: MetricKey.OfString = MetricKey.OfString("aws.dynamodb.projection")
        public val dynamodbProvisionedReadCapacity: MetricKey.OfDouble = MetricKey.OfDouble("aws.dynamodb.provisioned_read_capacity")
        public val dynamodbProvisionedWriteCapacity: MetricKey.OfDouble = MetricKey.OfDouble("aws.dynamodb.provisioned_write_capacity")
        public val dynamodbScanForward: MetricKey.OfBoolean = MetricKey.OfBoolean("aws.dynamodb.scan_forward")
        public val dynamodbScannedCount: MetricKey.OfLong = MetricKey.OfLong("aws.dynamodb.scanned_count")
        public val dynamodbSegment: MetricKey.OfLong = MetricKey.OfLong("aws.dynamodb.segment")
        public val dynamodbSelect: MetricKey.OfString = MetricKey.OfString("aws.dynamodb.select")
        public val dynamodbTableCount: MetricKey.OfLong = MetricKey.OfLong("aws.dynamodb.table_count")
        public val dynamodbTableNames: MetricKey.OfStringList = MetricKey.OfStringList("aws.dynamodb.table_names")
        public val dynamodbTotalSegments: MetricKey.OfLong = MetricKey.OfLong("aws.dynamodb.total_segments")
        public val ecsClusterArn: MetricKey.OfString = MetricKey.OfString("aws.ecs.cluster.arn")
        public val ecsContainerArn: MetricKey.OfString = MetricKey.OfString("aws.ecs.container.arn")
        public val ecsLaunchtype: MetricKey.OfString = MetricKey.OfString("aws.ecs.launchtype")
        public val ecsTaskArn: MetricKey.OfString = MetricKey.OfString("aws.ecs.task.arn")
        public val ecsTaskFamily: MetricKey.OfString = MetricKey.OfString("aws.ecs.task.family")
        public val ecsTaskId: MetricKey.OfString = MetricKey.OfString("aws.ecs.task.id")
        public val ecsTaskRevision: MetricKey.OfString = MetricKey.OfString("aws.ecs.task.revision")
        public val eksClusterArn: MetricKey.OfString = MetricKey.OfString("aws.eks.cluster.arn")
        public val extendedRequestId: MetricKey.OfString = MetricKey.OfString("aws.extended_request_id")
        public val kinesisStreamName: MetricKey.OfString = MetricKey.OfString("aws.kinesis.stream_name")
        public val lambdaInvokedArn: MetricKey.OfString = MetricKey.OfString("aws.lambda.invoked_arn")
        public val lambdaResourceMappingId: MetricKey.OfString = MetricKey.OfString("aws.lambda.resource_mapping.id")
        public val logGroupArns: MetricKey.OfStringList = MetricKey.OfStringList("aws.log.group.arns")
        public val logGroupNames: MetricKey.OfStringList = MetricKey.OfStringList("aws.log.group.names")
        public val logStreamArns: MetricKey.OfStringList = MetricKey.OfStringList("aws.log.stream.arns")
        public val logStreamNames: MetricKey.OfStringList = MetricKey.OfStringList("aws.log.stream.names")
        public val requestId: MetricKey.OfString = MetricKey.OfString("aws.request_id")
        public val s3Bucket: MetricKey.OfString = MetricKey.OfString("aws.s3.bucket")
        public val s3CopySource: MetricKey.OfString = MetricKey.OfString("aws.s3.copy_source")
        public val s3Delete: MetricKey.OfString = MetricKey.OfString("aws.s3.delete")
        public val s3Key: MetricKey.OfString = MetricKey.OfString("aws.s3.key")
        public val s3PartNumber: MetricKey.OfLong = MetricKey.OfLong("aws.s3.part_number")
        public val s3UploadId: MetricKey.OfString = MetricKey.OfString("aws.s3.upload_id")
        public val secretsmanagerSecretArn: MetricKey.OfString = MetricKey.OfString("aws.secretsmanager.secret.arn")
        public val snsTopicArn: MetricKey.OfString = MetricKey.OfString("aws.sns.topic.arn")
        public val sqsQueueUrl: MetricKey.OfString = MetricKey.OfString("aws.sqs.queue.url")
        public val stepFunctionsActivityArn: MetricKey.OfString = MetricKey.OfString("aws.step_functions.activity.arn")
        public val stepFunctionsStateMachineArn: MetricKey.OfString = MetricKey.OfString("aws.step_functions.state_machine.arn")
    }
    public object Az {
        public val namespace: MetricKey.OfString = MetricKey.OfString("az.namespace")
        public val serviceRequestId: MetricKey.OfString = MetricKey.OfString("az.service_request_id")
    }
    public object Azure {
        public val clientId: MetricKey.OfString = MetricKey.OfString("azure.client.id")
        public val cosmosdbConnectionMode: MetricKey.OfString = MetricKey.OfString("azure.cosmosdb.connection.mode")
        public val cosmosdbConsistencyLevel: MetricKey.OfString = MetricKey.OfString("azure.cosmosdb.consistency.level")
        public val cosmosdbOperationContactedRegions: MetricKey.OfStringList = MetricKey.OfStringList("azure.cosmosdb.operation.contacted_regions")
        public val cosmosdbOperationRequestCharge: MetricKey.OfDouble = MetricKey.OfDouble("azure.cosmosdb.operation.request_charge")
        public val cosmosdbRequestBodySize: MetricKey.OfLong = MetricKey.OfLong("azure.cosmosdb.request.body.size")
        public val cosmosdbResponseSubStatusCode: MetricKey.OfLong = MetricKey.OfLong("azure.cosmosdb.response.sub_status_code")
        public val resourceProviderNamespace: MetricKey.OfString = MetricKey.OfString("azure.resource_provider.namespace")
        public val serviceRequestId: MetricKey.OfString = MetricKey.OfString("azure.service.request.id")
    }
    public object Browser {
        public val brands: MetricKey.OfStringList = MetricKey.OfStringList("browser.brands")
        public val documentUrlFull: MetricKey.OfString = MetricKey.OfString("browser.document.url.full")
        public val language: MetricKey.OfString = MetricKey.OfString("browser.language")
        public val mobile: MetricKey.OfBoolean = MetricKey.OfBoolean("browser.mobile")
        public val platform: MetricKey.OfString = MetricKey.OfString("browser.platform")
    }
    public object Cassandra {
        public val consistencyLevel: MetricKey.OfString = MetricKey.OfString("cassandra.consistency.level")
        public val coordinatorDc: MetricKey.OfString = MetricKey.OfString("cassandra.coordinator.dc")
        public val coordinatorId: MetricKey.OfString = MetricKey.OfString("cassandra.coordinator.id")
        public val pageSize: MetricKey.OfLong = MetricKey.OfLong("cassandra.page.size")
        public val queryIdempotent: MetricKey.OfBoolean = MetricKey.OfBoolean("cassandra.query.idempotent")
        public val speculativeExecutionCount: MetricKey.OfLong = MetricKey.OfLong("cassandra.speculative_execution.count")
    }
    public object Cicd {
        public val pipelineActionName: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.action.name")
        public val pipelineName: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.name")
        public val pipelineResult: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.result")
        public val pipelineRunId: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.run.id")
        public val pipelineRunState: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.run.state")
        public val pipelineRunUrlFull: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.run.url.full")
        public val pipelineTaskName: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.task.name")
        public val pipelineTaskRunId: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.task.run.id")
        public val pipelineTaskRunResult: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.task.run.result")
        public val pipelineTaskRunUrlFull: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.task.run.url.full")
        public val pipelineTaskType: MetricKey.OfString = MetricKey.OfString("cicd.pipeline.task.type")
        public val systemComponent: MetricKey.OfString = MetricKey.OfString("cicd.system.component")
        public val workerId: MetricKey.OfString = MetricKey.OfString("cicd.worker.id")
        public val workerName: MetricKey.OfString = MetricKey.OfString("cicd.worker.name")
        public val workerState: MetricKey.OfString = MetricKey.OfString("cicd.worker.state")
        public val workerUrlFull: MetricKey.OfString = MetricKey.OfString("cicd.worker.url.full")
    }
    public object Client {
        public val address: MetricKey.OfString = MetricKey.OfString("client.address")
        public val port: MetricKey.OfLong = MetricKey.OfLong("client.port")
    }
    public object Cloud {
        public val accountId: MetricKey.OfString = MetricKey.OfString("cloud.account.id")
        public val availabilityZone: MetricKey.OfString = MetricKey.OfString("cloud.availability_zone")
        public val platform: MetricKey.OfString = MetricKey.OfString("cloud.platform")
        public val provider: MetricKey.OfString = MetricKey.OfString("cloud.provider")
        public val region: MetricKey.OfString = MetricKey.OfString("cloud.region")
        public val resourceId: MetricKey.OfString = MetricKey.OfString("cloud.resource_id")
    }
    public object Cloudevents {
        public val eventId: MetricKey.OfString = MetricKey.OfString("cloudevents.event_id")
        public val eventSource: MetricKey.OfString = MetricKey.OfString("cloudevents.event_source")
        public val eventSpecVersion: MetricKey.OfString = MetricKey.OfString("cloudevents.event_spec_version")
        public val eventSubject: MetricKey.OfString = MetricKey.OfString("cloudevents.event_subject")
        public val eventType: MetricKey.OfString = MetricKey.OfString("cloudevents.event_type")
    }
    public object Cloudfoundry {
        public val appId: MetricKey.OfString = MetricKey.OfString("cloudfoundry.app.id")
        public val appInstanceId: MetricKey.OfString = MetricKey.OfString("cloudfoundry.app.instance.id")
        public val appName: MetricKey.OfString = MetricKey.OfString("cloudfoundry.app.name")
        public val orgId: MetricKey.OfString = MetricKey.OfString("cloudfoundry.org.id")
        public val orgName: MetricKey.OfString = MetricKey.OfString("cloudfoundry.org.name")
        public val processId: MetricKey.OfString = MetricKey.OfString("cloudfoundry.process.id")
        public val processType: MetricKey.OfString = MetricKey.OfString("cloudfoundry.process.type")
        public val spaceId: MetricKey.OfString = MetricKey.OfString("cloudfoundry.space.id")
        public val spaceName: MetricKey.OfString = MetricKey.OfString("cloudfoundry.space.name")
        public val systemId: MetricKey.OfString = MetricKey.OfString("cloudfoundry.system.id")
        public val systemInstanceId: MetricKey.OfString = MetricKey.OfString("cloudfoundry.system.instance.id")
    }
    public object Code {
        public val column: MetricKey.OfLong = MetricKey.OfLong("code.column")
        public val columnNumber: MetricKey.OfLong = MetricKey.OfLong("code.column.number")
        public val filePath: MetricKey.OfString = MetricKey.OfString("code.file.path")
        public val filepath: MetricKey.OfString = MetricKey.OfString("code.filepath")
        public val function: MetricKey.OfString = MetricKey.OfString("code.function")
        public val functionName: MetricKey.OfString = MetricKey.OfString("code.function.name")
        public val lineNumber: MetricKey.OfLong = MetricKey.OfLong("code.line.number")
        public val lineno: MetricKey.OfLong = MetricKey.OfLong("code.lineno")
        public val namespace: MetricKey.OfString = MetricKey.OfString("code.namespace")
        public val stacktrace: MetricKey.OfString = MetricKey.OfString("code.stacktrace")
    }
    public object Container {
        public val command: MetricKey.OfString = MetricKey.OfString("container.command")
        public val commandArgs: MetricKey.OfStringList = MetricKey.OfStringList("container.command_args")
        public val commandLine: MetricKey.OfString = MetricKey.OfString("container.command_line")
        public val cpuState: MetricKey.OfString = MetricKey.OfString("container.cpu.state")
        public val csiPluginName: MetricKey.OfString = MetricKey.OfString("container.csi.plugin.name")
        public val csiVolumeId: MetricKey.OfString = MetricKey.OfString("container.csi.volume.id")
        public val id: MetricKey.OfString = MetricKey.OfString("container.id")
        public val imageId: MetricKey.OfString = MetricKey.OfString("container.image.id")
        public val imageName: MetricKey.OfString = MetricKey.OfString("container.image.name")
        public val imageRepoDigests: MetricKey.OfStringList = MetricKey.OfStringList("container.image.repo_digests")
        public val imageTags: MetricKey.OfStringList = MetricKey.OfStringList("container.image.tags")
        public val name: MetricKey.OfString = MetricKey.OfString("container.name")
        public val runtime: MetricKey.OfString = MetricKey.OfString("container.runtime")
        public val runtimeDescription: MetricKey.OfString = MetricKey.OfString("container.runtime.description")
        public val runtimeName: MetricKey.OfString = MetricKey.OfString("container.runtime.name")
        public val runtimeVersion: MetricKey.OfString = MetricKey.OfString("container.runtime.version")
    }
    public object Cpu {
        public val logicalNumber: MetricKey.OfLong = MetricKey.OfLong("cpu.logical_number")
        public val mode: MetricKey.OfString = MetricKey.OfString("cpu.mode")
    }
    public object Cpython {
        public val gcGeneration: MetricKey.OfString = MetricKey.OfString("cpython.gc.generation")
    }
    public object Db {
        public val cassandraConsistencyLevel: MetricKey.OfString = MetricKey.OfString("db.cassandra.consistency_level")
        public val cassandraCoordinatorDc: MetricKey.OfString = MetricKey.OfString("db.cassandra.coordinator.dc")
        public val cassandraCoordinatorId: MetricKey.OfString = MetricKey.OfString("db.cassandra.coordinator.id")
        public val cassandraIdempotence: MetricKey.OfBoolean = MetricKey.OfBoolean("db.cassandra.idempotence")
        public val cassandraPageSize: MetricKey.OfLong = MetricKey.OfLong("db.cassandra.page_size")
        public val cassandraSpeculativeExecutionCount: MetricKey.OfLong = MetricKey.OfLong("db.cassandra.speculative_execution_count")
        public val cassandraTable: MetricKey.OfString = MetricKey.OfString("db.cassandra.table")
        public val clientConnectionPoolName: MetricKey.OfString = MetricKey.OfString("db.client.connection.pool.name")
        public val clientConnectionState: MetricKey.OfString = MetricKey.OfString("db.client.connection.state")
        public val clientConnectionsPoolName: MetricKey.OfString = MetricKey.OfString("db.client.connections.pool.name")
        public val clientConnectionsState: MetricKey.OfString = MetricKey.OfString("db.client.connections.state")
        public val collectionName: MetricKey.OfString = MetricKey.OfString("db.collection.name")
        public val connectionString: MetricKey.OfString = MetricKey.OfString("db.connection_string")
        public val cosmosdbClientId: MetricKey.OfString = MetricKey.OfString("db.cosmosdb.client_id")
        public val cosmosdbConnectionMode: MetricKey.OfString = MetricKey.OfString("db.cosmosdb.connection_mode")
        public val cosmosdbConsistencyLevel: MetricKey.OfString = MetricKey.OfString("db.cosmosdb.consistency_level")
        public val cosmosdbContainer: MetricKey.OfString = MetricKey.OfString("db.cosmosdb.container")
        public val cosmosdbOperationType: MetricKey.OfString = MetricKey.OfString("db.cosmosdb.operation_type")
        public val cosmosdbRegionsContacted: MetricKey.OfStringList = MetricKey.OfStringList("db.cosmosdb.regions_contacted")
        public val cosmosdbRequestCharge: MetricKey.OfDouble = MetricKey.OfDouble("db.cosmosdb.request_charge")
        public val cosmosdbRequestContentLength: MetricKey.OfLong = MetricKey.OfLong("db.cosmosdb.request_content_length")
        public val cosmosdbStatusCode: MetricKey.OfLong = MetricKey.OfLong("db.cosmosdb.status_code")
        public val cosmosdbSubStatusCode: MetricKey.OfLong = MetricKey.OfLong("db.cosmosdb.sub_status_code")
        public val elasticsearchClusterName: MetricKey.OfString = MetricKey.OfString("db.elasticsearch.cluster.name")
        public val elasticsearchNodeName: MetricKey.OfString = MetricKey.OfString("db.elasticsearch.node.name")
        public val instanceId: MetricKey.OfString = MetricKey.OfString("db.instance.id")
        public val jdbcDriverClassname: MetricKey.OfString = MetricKey.OfString("db.jdbc.driver_classname")
        public val mongodbCollection: MetricKey.OfString = MetricKey.OfString("db.mongodb.collection")
        public val mssqlInstanceName: MetricKey.OfString = MetricKey.OfString("db.mssql.instance_name")
        public val name: MetricKey.OfString = MetricKey.OfString("db.name")
        public val namespace: MetricKey.OfString = MetricKey.OfString("db.namespace")
        public val operation: MetricKey.OfString = MetricKey.OfString("db.operation")
        public val operationBatchSize: MetricKey.OfLong = MetricKey.OfLong("db.operation.batch.size")
        public val operationName: MetricKey.OfString = MetricKey.OfString("db.operation.name")
        public val querySummary: MetricKey.OfString = MetricKey.OfString("db.query.summary")
        public val queryText: MetricKey.OfString = MetricKey.OfString("db.query.text")
        public val redisDatabaseIndex: MetricKey.OfLong = MetricKey.OfLong("db.redis.database_index")
        public val responseReturnedRows: MetricKey.OfLong = MetricKey.OfLong("db.response.returned_rows")
        public val responseStatusCode: MetricKey.OfString = MetricKey.OfString("db.response.status_code")
        public val sqlTable: MetricKey.OfString = MetricKey.OfString("db.sql.table")
        public val statement: MetricKey.OfString = MetricKey.OfString("db.statement")
        public val storedProcedureName: MetricKey.OfString = MetricKey.OfString("db.stored_procedure.name")
        public val system: MetricKey.OfString = MetricKey.OfString("db.system")
        public val systemName: MetricKey.OfString = MetricKey.OfString("db.system.name")
        public val user: MetricKey.OfString = MetricKey.OfString("db.user")
    }
    public object Deployment {
        public val environment: MetricKey.OfString = MetricKey.OfString("deployment.environment")
        public val environmentName: MetricKey.OfString = MetricKey.OfString("deployment.environment.name")
        public val id: MetricKey.OfString = MetricKey.OfString("deployment.id")
        public val name: MetricKey.OfString = MetricKey.OfString("deployment.name")
        public val status: MetricKey.OfString = MetricKey.OfString("deployment.status")
    }
    public object Destination {
        public val address: MetricKey.OfString = MetricKey.OfString("destination.address")
        public val port: MetricKey.OfLong = MetricKey.OfLong("destination.port")
    }
    public object Device {
        public val id: MetricKey.OfString = MetricKey.OfString("device.id")
        public val manufacturer: MetricKey.OfString = MetricKey.OfString("device.manufacturer")
        public val modelIdentifier: MetricKey.OfString = MetricKey.OfString("device.model.identifier")
        public val modelName: MetricKey.OfString = MetricKey.OfString("device.model.name")
    }
    public object Disk {
        public val ioDirection: MetricKey.OfString = MetricKey.OfString("disk.io.direction")
    }
    public object Dns {
        public val answers: MetricKey.OfStringList = MetricKey.OfStringList("dns.answers")
        public val questionName: MetricKey.OfString = MetricKey.OfString("dns.question.name")
    }
    public object Dotnet {
        public val gcHeapGeneration: MetricKey.OfString = MetricKey.OfString("dotnet.gc.heap.generation")
    }
    public object Elasticsearch {
        public val nodeName: MetricKey.OfString = MetricKey.OfString("elasticsearch.node.name")
    }
    public object Enduser {
        public val id: MetricKey.OfString = MetricKey.OfString("enduser.id")
        public val pseudoId: MetricKey.OfString = MetricKey.OfString("enduser.pseudo.id")
        public val role: MetricKey.OfString = MetricKey.OfString("enduser.role")
        public val scope: MetricKey.OfString = MetricKey.OfString("enduser.scope")
    }
    public object Error {
        public val message: MetricKey.OfString = MetricKey.OfString("error.message")
        public val type: MetricKey.OfString = MetricKey.OfString("error.type")
    }
    public object Event {
        public val name: MetricKey.OfString = MetricKey.OfString("event.name")
    }
    public object Exception {
        public val escaped: MetricKey.OfBoolean = MetricKey.OfBoolean("exception.escaped")
        public val message: MetricKey.OfString = MetricKey.OfString("exception.message")
        public val stacktrace: MetricKey.OfString = MetricKey.OfString("exception.stacktrace")
        public val type: MetricKey.OfString = MetricKey.OfString("exception.type")
    }
    public object Faas {
        public val coldstart: MetricKey.OfBoolean = MetricKey.OfBoolean("faas.coldstart")
        public val cron: MetricKey.OfString = MetricKey.OfString("faas.cron")
        public val documentCollection: MetricKey.OfString = MetricKey.OfString("faas.document.collection")
        public val documentName: MetricKey.OfString = MetricKey.OfString("faas.document.name")
        public val documentOperation: MetricKey.OfString = MetricKey.OfString("faas.document.operation")
        public val documentTime: MetricKey.OfString = MetricKey.OfString("faas.document.time")
        public val instance: MetricKey.OfString = MetricKey.OfString("faas.instance")
        public val invocationId: MetricKey.OfString = MetricKey.OfString("faas.invocation_id")
        public val invokedName: MetricKey.OfString = MetricKey.OfString("faas.invoked_name")
        public val invokedProvider: MetricKey.OfString = MetricKey.OfString("faas.invoked_provider")
        public val invokedRegion: MetricKey.OfString = MetricKey.OfString("faas.invoked_region")
        public val maxMemory: MetricKey.OfLong = MetricKey.OfLong("faas.max_memory")
        public val name: MetricKey.OfString = MetricKey.OfString("faas.name")
        public val time: MetricKey.OfString = MetricKey.OfString("faas.time")
        public val trigger: MetricKey.OfString = MetricKey.OfString("faas.trigger")
        public val version: MetricKey.OfString = MetricKey.OfString("faas.version")
    }
    public object FeatureFlag {
        public val contextId: MetricKey.OfString = MetricKey.OfString("feature_flag.context.id")
        public val errorMessage: MetricKey.OfString = MetricKey.OfString("feature_flag.error.message")
        public val evaluationErrorMessage: MetricKey.OfString = MetricKey.OfString("feature_flag.evaluation.error.message")
        public val evaluationReason: MetricKey.OfString = MetricKey.OfString("feature_flag.evaluation.reason")
        public val key: MetricKey.OfString = MetricKey.OfString("feature_flag.key")
        public val providerName: MetricKey.OfString = MetricKey.OfString("feature_flag.provider.name")
        public val resultReason: MetricKey.OfString = MetricKey.OfString("feature_flag.result.reason")
        public val resultVariant: MetricKey.OfString = MetricKey.OfString("feature_flag.result.variant")
        public val setId: MetricKey.OfString = MetricKey.OfString("feature_flag.set.id")
        public val variant: MetricKey.OfString = MetricKey.OfString("feature_flag.variant")
        public val version: MetricKey.OfString = MetricKey.OfString("feature_flag.version")
    }
    public object File {
        public val accessed: MetricKey.OfString = MetricKey.OfString("file.accessed")
        public val attributes: MetricKey.OfStringList = MetricKey.OfStringList("file.attributes")
        public val changed: MetricKey.OfString = MetricKey.OfString("file.changed")
        public val created: MetricKey.OfString = MetricKey.OfString("file.created")
        public val directory: MetricKey.OfString = MetricKey.OfString("file.directory")
        public val extension: MetricKey.OfString = MetricKey.OfString("file.extension")
        public val forkName: MetricKey.OfString = MetricKey.OfString("file.fork_name")
        public val groupId: MetricKey.OfString = MetricKey.OfString("file.group.id")
        public val groupName: MetricKey.OfString = MetricKey.OfString("file.group.name")
        public val inode: MetricKey.OfString = MetricKey.OfString("file.inode")
        public val lockMechanism: MetricKey.OfString = MetricKey.OfString("file.lock.mechanism")
        public val lockMode: MetricKey.OfString = MetricKey.OfString("file.lock.mode")
        public val lockType: MetricKey.OfString = MetricKey.OfString("file.lock.type")
        public val mode: MetricKey.OfString = MetricKey.OfString("file.mode")
        public val modified: MetricKey.OfString = MetricKey.OfString("file.modified")
        public val name: MetricKey.OfString = MetricKey.OfString("file.name")
        public val ownerId: MetricKey.OfString = MetricKey.OfString("file.owner.id")
        public val ownerName: MetricKey.OfString = MetricKey.OfString("file.owner.name")
        public val path: MetricKey.OfString = MetricKey.OfString("file.path")
        public val size: MetricKey.OfLong = MetricKey.OfLong("file.size")
        public val symbolicLinkTargetPath: MetricKey.OfString = MetricKey.OfString("file.symbolic_link.target_path")
    }
    public object Gcp {
        public val apphubApplicationContainer: MetricKey.OfString = MetricKey.OfString("gcp.apphub.application.container")
        public val apphubApplicationId: MetricKey.OfString = MetricKey.OfString("gcp.apphub.application.id")
        public val apphubApplicationLocation: MetricKey.OfString = MetricKey.OfString("gcp.apphub.application.location")
        public val apphubServiceCriticalityType: MetricKey.OfString = MetricKey.OfString("gcp.apphub.service.criticality_type")
        public val apphubServiceEnvironmentType: MetricKey.OfString = MetricKey.OfString("gcp.apphub.service.environment_type")
        public val apphubServiceId: MetricKey.OfString = MetricKey.OfString("gcp.apphub.service.id")
        public val apphubWorkloadCriticalityType: MetricKey.OfString = MetricKey.OfString("gcp.apphub.workload.criticality_type")
        public val apphubWorkloadEnvironmentType: MetricKey.OfString = MetricKey.OfString("gcp.apphub.workload.environment_type")
        public val apphubWorkloadId: MetricKey.OfString = MetricKey.OfString("gcp.apphub.workload.id")
        public val apphubDestinationApplicationContainer: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.application.container")
        public val apphubDestinationApplicationId: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.application.id")
        public val apphubDestinationApplicationLocation: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.application.location")
        public val apphubDestinationServiceCriticalityType: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.service.criticality_type")
        public val apphubDestinationServiceEnvironmentType: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.service.environment_type")
        public val apphubDestinationServiceId: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.service.id")
        public val apphubDestinationWorkloadCriticalityType: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.workload.criticality_type")
        public val apphubDestinationWorkloadEnvironmentType: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.workload.environment_type")
        public val apphubDestinationWorkloadId: MetricKey.OfString = MetricKey.OfString("gcp.apphub_destination.workload.id")
        public val clientService: MetricKey.OfString = MetricKey.OfString("gcp.client.service")
        public val cloudRunJobExecution: MetricKey.OfString = MetricKey.OfString("gcp.cloud_run.job.execution")
        public val cloudRunJobTaskIndex: MetricKey.OfLong = MetricKey.OfLong("gcp.cloud_run.job.task_index")
        public val gceInstanceHostname: MetricKey.OfString = MetricKey.OfString("gcp.gce.instance.hostname")
        public val gceInstanceName: MetricKey.OfString = MetricKey.OfString("gcp.gce.instance.name")
        public val gceInstanceGroupManagerName: MetricKey.OfString = MetricKey.OfString("gcp.gce.instance_group_manager.name")
        public val gceInstanceGroupManagerRegion: MetricKey.OfString = MetricKey.OfString("gcp.gce.instance_group_manager.region")
        public val gceInstanceGroupManagerZone: MetricKey.OfString = MetricKey.OfString("gcp.gce.instance_group_manager.zone")
    }
    public object GenAi {
        public val agentDescription: MetricKey.OfString = MetricKey.OfString("gen_ai.agent.description")
        public val agentId: MetricKey.OfString = MetricKey.OfString("gen_ai.agent.id")
        public val agentName: MetricKey.OfString = MetricKey.OfString("gen_ai.agent.name")
        public val agentVersion: MetricKey.OfString = MetricKey.OfString("gen_ai.agent.version")
        public val completion: MetricKey.OfString = MetricKey.OfString("gen_ai.completion")
        public val conversationId: MetricKey.OfString = MetricKey.OfString("gen_ai.conversation.id")
        public val dataSourceId: MetricKey.OfString = MetricKey.OfString("gen_ai.data_source.id")
        public val embeddingsDimensionCount: MetricKey.OfLong = MetricKey.OfLong("gen_ai.embeddings.dimension.count")
        public val evaluationExplanation: MetricKey.OfString = MetricKey.OfString("gen_ai.evaluation.explanation")
        public val evaluationName: MetricKey.OfString = MetricKey.OfString("gen_ai.evaluation.name")
        public val evaluationScoreLabel: MetricKey.OfString = MetricKey.OfString("gen_ai.evaluation.score.label")
        public val evaluationScoreValue: MetricKey.OfDouble = MetricKey.OfDouble("gen_ai.evaluation.score.value")
        public val openaiRequestResponseFormat: MetricKey.OfString = MetricKey.OfString("gen_ai.openai.request.response_format")
        public val openaiRequestSeed: MetricKey.OfLong = MetricKey.OfLong("gen_ai.openai.request.seed")
        public val openaiRequestServiceTier: MetricKey.OfString = MetricKey.OfString("gen_ai.openai.request.service_tier")
        public val openaiResponseServiceTier: MetricKey.OfString = MetricKey.OfString("gen_ai.openai.response.service_tier")
        public val openaiResponseSystemFingerprint: MetricKey.OfString = MetricKey.OfString("gen_ai.openai.response.system_fingerprint")
        public val operationName: MetricKey.OfString = MetricKey.OfString("gen_ai.operation.name")
        public val outputType: MetricKey.OfString = MetricKey.OfString("gen_ai.output.type")
        public val prompt: MetricKey.OfString = MetricKey.OfString("gen_ai.prompt")
        public val promptName: MetricKey.OfString = MetricKey.OfString("gen_ai.prompt.name")
        public val providerName: MetricKey.OfString = MetricKey.OfString("gen_ai.provider.name")
        public val requestChoiceCount: MetricKey.OfLong = MetricKey.OfLong("gen_ai.request.choice.count")
        public val requestEncodingFormats: MetricKey.OfStringList = MetricKey.OfStringList("gen_ai.request.encoding_formats")
        public val requestFrequencyPenalty: MetricKey.OfDouble = MetricKey.OfDouble("gen_ai.request.frequency_penalty")
        public val requestMaxTokens: MetricKey.OfLong = MetricKey.OfLong("gen_ai.request.max_tokens")
        public val requestModel: MetricKey.OfString = MetricKey.OfString("gen_ai.request.model")
        public val requestPresencePenalty: MetricKey.OfDouble = MetricKey.OfDouble("gen_ai.request.presence_penalty")
        public val requestSeed: MetricKey.OfLong = MetricKey.OfLong("gen_ai.request.seed")
        public val requestStopSequences: MetricKey.OfStringList = MetricKey.OfStringList("gen_ai.request.stop_sequences")
        public val requestStream: MetricKey.OfBoolean = MetricKey.OfBoolean("gen_ai.request.stream")
        public val requestTemperature: MetricKey.OfDouble = MetricKey.OfDouble("gen_ai.request.temperature")
        public val requestTopK: MetricKey.OfDouble = MetricKey.OfDouble("gen_ai.request.top_k")
        public val requestTopP: MetricKey.OfDouble = MetricKey.OfDouble("gen_ai.request.top_p")
        public val responseFinishReasons: MetricKey.OfStringList = MetricKey.OfStringList("gen_ai.response.finish_reasons")
        public val responseId: MetricKey.OfString = MetricKey.OfString("gen_ai.response.id")
        public val responseModel: MetricKey.OfString = MetricKey.OfString("gen_ai.response.model")
        public val responseTimeToFirstChunk: MetricKey.OfDouble = MetricKey.OfDouble("gen_ai.response.time_to_first_chunk")
        public val retrievalQueryText: MetricKey.OfString = MetricKey.OfString("gen_ai.retrieval.query.text")
        public val system: MetricKey.OfString = MetricKey.OfString("gen_ai.system")
        public val tokenType: MetricKey.OfString = MetricKey.OfString("gen_ai.token.type")
        public val toolCallId: MetricKey.OfString = MetricKey.OfString("gen_ai.tool.call.id")
        public val toolDescription: MetricKey.OfString = MetricKey.OfString("gen_ai.tool.description")
        public val toolName: MetricKey.OfString = MetricKey.OfString("gen_ai.tool.name")
        public val toolType: MetricKey.OfString = MetricKey.OfString("gen_ai.tool.type")
        public val usageCacheCreationInputTokens: MetricKey.OfLong = MetricKey.OfLong("gen_ai.usage.cache_creation.input_tokens")
        public val usageCacheReadInputTokens: MetricKey.OfLong = MetricKey.OfLong("gen_ai.usage.cache_read.input_tokens")
        public val usageCompletionTokens: MetricKey.OfLong = MetricKey.OfLong("gen_ai.usage.completion_tokens")
        public val usageInputTokens: MetricKey.OfLong = MetricKey.OfLong("gen_ai.usage.input_tokens")
        public val usageOutputTokens: MetricKey.OfLong = MetricKey.OfLong("gen_ai.usage.output_tokens")
        public val usagePromptTokens: MetricKey.OfLong = MetricKey.OfLong("gen_ai.usage.prompt_tokens")
        public val usageReasoningOutputTokens: MetricKey.OfLong = MetricKey.OfLong("gen_ai.usage.reasoning.output_tokens")
        public val workflowName: MetricKey.OfString = MetricKey.OfString("gen_ai.workflow.name")
    }
    public object Geo {
        public val continentCode: MetricKey.OfString = MetricKey.OfString("geo.continent.code")
        public val countryIsoCode: MetricKey.OfString = MetricKey.OfString("geo.country.iso_code")
        public val localityName: MetricKey.OfString = MetricKey.OfString("geo.locality.name")
        public val locationLat: MetricKey.OfDouble = MetricKey.OfDouble("geo.location.lat")
        public val locationLon: MetricKey.OfDouble = MetricKey.OfDouble("geo.location.lon")
        public val postalCode: MetricKey.OfString = MetricKey.OfString("geo.postal_code")
        public val regionIsoCode: MetricKey.OfString = MetricKey.OfString("geo.region.iso_code")
    }
    public object Go {
        public val cpuDetailedState: MetricKey.OfString = MetricKey.OfString("go.cpu.detailed_state")
        public val cpuState: MetricKey.OfString = MetricKey.OfString("go.cpu.state")
        public val memoryDetailedType: MetricKey.OfString = MetricKey.OfString("go.memory.detailed_type")
        public val memoryType: MetricKey.OfString = MetricKey.OfString("go.memory.type")
    }
    public object Graphql {
        public val document: MetricKey.OfString = MetricKey.OfString("graphql.document")
        public val operationName: MetricKey.OfString = MetricKey.OfString("graphql.operation.name")
        public val operationType: MetricKey.OfString = MetricKey.OfString("graphql.operation.type")
    }
    public object Heroku {
        public val appId: MetricKey.OfString = MetricKey.OfString("heroku.app.id")
        public val releaseCommit: MetricKey.OfString = MetricKey.OfString("heroku.release.commit")
        public val releaseCreationTimestamp: MetricKey.OfString = MetricKey.OfString("heroku.release.creation_timestamp")
    }
    public object Host {
        public val arch: MetricKey.OfString = MetricKey.OfString("host.arch")
        public val cpuCacheL2Size: MetricKey.OfLong = MetricKey.OfLong("host.cpu.cache.l2.size")
        public val cpuFamily: MetricKey.OfString = MetricKey.OfString("host.cpu.family")
        public val cpuModelId: MetricKey.OfString = MetricKey.OfString("host.cpu.model.id")
        public val cpuModelName: MetricKey.OfString = MetricKey.OfString("host.cpu.model.name")
        public val cpuStepping: MetricKey.OfString = MetricKey.OfString("host.cpu.stepping")
        public val cpuVendorId: MetricKey.OfString = MetricKey.OfString("host.cpu.vendor.id")
        public val id: MetricKey.OfString = MetricKey.OfString("host.id")
        public val imageId: MetricKey.OfString = MetricKey.OfString("host.image.id")
        public val imageName: MetricKey.OfString = MetricKey.OfString("host.image.name")
        public val imageVersion: MetricKey.OfString = MetricKey.OfString("host.image.version")
        public val ip: MetricKey.OfStringList = MetricKey.OfStringList("host.ip")
        public val mac: MetricKey.OfStringList = MetricKey.OfStringList("host.mac")
        public val name: MetricKey.OfString = MetricKey.OfString("host.name")
        public val type: MetricKey.OfString = MetricKey.OfString("host.type")
    }
    public object Http {
        public val clientIp: MetricKey.OfString = MetricKey.OfString("http.client_ip")
        public val connectionState: MetricKey.OfString = MetricKey.OfString("http.connection.state")
        public val flavor: MetricKey.OfString = MetricKey.OfString("http.flavor")
        public val host: MetricKey.OfString = MetricKey.OfString("http.host")
        public val method: MetricKey.OfString = MetricKey.OfString("http.method")
        public val requestBodySize: MetricKey.OfLong = MetricKey.OfLong("http.request.body.size")
        public val requestMethod: MetricKey.OfString = MetricKey.OfString("http.request.method")
        public val requestMethodOriginal: MetricKey.OfString = MetricKey.OfString("http.request.method_original")
        public val requestResendCount: MetricKey.OfLong = MetricKey.OfLong("http.request.resend_count")
        public val requestSize: MetricKey.OfLong = MetricKey.OfLong("http.request.size")
        public val requestContentLength: MetricKey.OfLong = MetricKey.OfLong("http.request_content_length")
        public val requestContentLengthUncompressed: MetricKey.OfLong = MetricKey.OfLong("http.request_content_length_uncompressed")
        public val responseBodySize: MetricKey.OfLong = MetricKey.OfLong("http.response.body.size")
        public val responseSize: MetricKey.OfLong = MetricKey.OfLong("http.response.size")
        public val responseStatusCode: MetricKey.OfLong = MetricKey.OfLong("http.response.status_code")
        public val responseContentLength: MetricKey.OfLong = MetricKey.OfLong("http.response_content_length")
        public val responseContentLengthUncompressed: MetricKey.OfLong = MetricKey.OfLong("http.response_content_length_uncompressed")
        public val route: MetricKey.OfString = MetricKey.OfString("http.route")
        public val scheme: MetricKey.OfString = MetricKey.OfString("http.scheme")
        public val serverName: MetricKey.OfString = MetricKey.OfString("http.server_name")
        public val statusCode: MetricKey.OfLong = MetricKey.OfLong("http.status_code")
        public val target: MetricKey.OfString = MetricKey.OfString("http.target")
        public val url: MetricKey.OfString = MetricKey.OfString("http.url")
        public val userAgent: MetricKey.OfString = MetricKey.OfString("http.user_agent")
    }
    public object Hw {
        public val batteryCapacity: MetricKey.OfString = MetricKey.OfString("hw.battery.capacity")
        public val batteryChemistry: MetricKey.OfString = MetricKey.OfString("hw.battery.chemistry")
        public val batteryState: MetricKey.OfString = MetricKey.OfString("hw.battery.state")
        public val biosVersion: MetricKey.OfString = MetricKey.OfString("hw.bios_version")
        public val driverVersion: MetricKey.OfString = MetricKey.OfString("hw.driver_version")
        public val enclosureType: MetricKey.OfString = MetricKey.OfString("hw.enclosure.type")
        public val firmwareVersion: MetricKey.OfString = MetricKey.OfString("hw.firmware_version")
        public val gpuTask: MetricKey.OfString = MetricKey.OfString("hw.gpu.task")
        public val id: MetricKey.OfString = MetricKey.OfString("hw.id")
        public val limitType: MetricKey.OfString = MetricKey.OfString("hw.limit_type")
        public val logicalDiskRaidLevel: MetricKey.OfString = MetricKey.OfString("hw.logical_disk.raid_level")
        public val logicalDiskState: MetricKey.OfString = MetricKey.OfString("hw.logical_disk.state")
        public val memoryType: MetricKey.OfString = MetricKey.OfString("hw.memory.type")
        public val model: MetricKey.OfString = MetricKey.OfString("hw.model")
        public val name: MetricKey.OfString = MetricKey.OfString("hw.name")
        public val networkLogicalAddresses: MetricKey.OfStringList = MetricKey.OfStringList("hw.network.logical_addresses")
        public val networkPhysicalAddress: MetricKey.OfString = MetricKey.OfString("hw.network.physical_address")
        public val parent: MetricKey.OfString = MetricKey.OfString("hw.parent")
        public val physicalDiskSmartAttribute: MetricKey.OfString = MetricKey.OfString("hw.physical_disk.smart_attribute")
        public val physicalDiskState: MetricKey.OfString = MetricKey.OfString("hw.physical_disk.state")
        public val physicalDiskType: MetricKey.OfString = MetricKey.OfString("hw.physical_disk.type")
        public val sensorLocation: MetricKey.OfString = MetricKey.OfString("hw.sensor_location")
        public val serialNumber: MetricKey.OfString = MetricKey.OfString("hw.serial_number")
        public val state: MetricKey.OfString = MetricKey.OfString("hw.state")
        public val tapeDriveOperationType: MetricKey.OfString = MetricKey.OfString("hw.tape_drive.operation_type")
        public val type: MetricKey.OfString = MetricKey.OfString("hw.type")
        public val vendor: MetricKey.OfString = MetricKey.OfString("hw.vendor")
    }
    public object Ios {
        public val appState: MetricKey.OfString = MetricKey.OfString("ios.app.state")
        public val state: MetricKey.OfString = MetricKey.OfString("ios.state")
    }
    public object Jsonrpc {
        public val protocolVersion: MetricKey.OfString = MetricKey.OfString("jsonrpc.protocol.version")
        public val requestId: MetricKey.OfString = MetricKey.OfString("jsonrpc.request.id")
    }
    public object Jvm {
        public val bufferPoolName: MetricKey.OfString = MetricKey.OfString("jvm.buffer.pool.name")
        public val gcAction: MetricKey.OfString = MetricKey.OfString("jvm.gc.action")
        public val gcCause: MetricKey.OfString = MetricKey.OfString("jvm.gc.cause")
        public val gcName: MetricKey.OfString = MetricKey.OfString("jvm.gc.name")
        public val memoryPoolName: MetricKey.OfString = MetricKey.OfString("jvm.memory.pool.name")
        public val memoryType: MetricKey.OfString = MetricKey.OfString("jvm.memory.type")
        public val threadDaemon: MetricKey.OfBoolean = MetricKey.OfBoolean("jvm.thread.daemon")
        public val threadState: MetricKey.OfString = MetricKey.OfString("jvm.thread.state")
    }
    public object K8s {
        public val clusterName: MetricKey.OfString = MetricKey.OfString("k8s.cluster.name")
        public val clusterUid: MetricKey.OfString = MetricKey.OfString("k8s.cluster.uid")
        public val containerEphemeralStorageFsType: MetricKey.OfString = MetricKey.OfString("k8s.container.ephemeral_storage.fs_type")
        public val containerName: MetricKey.OfString = MetricKey.OfString("k8s.container.name")
        public val containerRestartCount: MetricKey.OfLong = MetricKey.OfLong("k8s.container.restart_count")
        public val containerStatusLastTerminatedReason: MetricKey.OfString = MetricKey.OfString("k8s.container.status.last_terminated_reason")
        public val containerStatusReason: MetricKey.OfString = MetricKey.OfString("k8s.container.status.reason")
        public val containerStatusState: MetricKey.OfString = MetricKey.OfString("k8s.container.status.state")
        public val cronjobName: MetricKey.OfString = MetricKey.OfString("k8s.cronjob.name")
        public val cronjobUid: MetricKey.OfString = MetricKey.OfString("k8s.cronjob.uid")
        public val daemonsetName: MetricKey.OfString = MetricKey.OfString("k8s.daemonset.name")
        public val daemonsetUid: MetricKey.OfString = MetricKey.OfString("k8s.daemonset.uid")
        public val deploymentName: MetricKey.OfString = MetricKey.OfString("k8s.deployment.name")
        public val deploymentUid: MetricKey.OfString = MetricKey.OfString("k8s.deployment.uid")
        public val hpaMetricType: MetricKey.OfString = MetricKey.OfString("k8s.hpa.metric.type")
        public val hpaName: MetricKey.OfString = MetricKey.OfString("k8s.hpa.name")
        public val hpaScaletargetrefApiVersion: MetricKey.OfString = MetricKey.OfString("k8s.hpa.scaletargetref.api_version")
        public val hpaScaletargetrefKind: MetricKey.OfString = MetricKey.OfString("k8s.hpa.scaletargetref.kind")
        public val hpaScaletargetrefName: MetricKey.OfString = MetricKey.OfString("k8s.hpa.scaletargetref.name")
        public val hpaUid: MetricKey.OfString = MetricKey.OfString("k8s.hpa.uid")
        public val hugepageSize: MetricKey.OfString = MetricKey.OfString("k8s.hugepage.size")
        public val jobName: MetricKey.OfString = MetricKey.OfString("k8s.job.name")
        public val jobUid: MetricKey.OfString = MetricKey.OfString("k8s.job.uid")
        public val namespaceName: MetricKey.OfString = MetricKey.OfString("k8s.namespace.name")
        public val namespacePhase: MetricKey.OfString = MetricKey.OfString("k8s.namespace.phase")
        public val nodeConditionStatus: MetricKey.OfString = MetricKey.OfString("k8s.node.condition.status")
        public val nodeConditionType: MetricKey.OfString = MetricKey.OfString("k8s.node.condition.type")
        public val nodeName: MetricKey.OfString = MetricKey.OfString("k8s.node.name")
        public val nodeSystemContainerName: MetricKey.OfString = MetricKey.OfString("k8s.node.system_container.name")
        public val nodeUid: MetricKey.OfString = MetricKey.OfString("k8s.node.uid")
        public val persistentvolumeName: MetricKey.OfString = MetricKey.OfString("k8s.persistentvolume.name")
        public val persistentvolumeReclaimPolicy: MetricKey.OfString = MetricKey.OfString("k8s.persistentvolume.reclaim_policy")
        public val persistentvolumeStatusPhase: MetricKey.OfString = MetricKey.OfString("k8s.persistentvolume.status.phase")
        public val persistentvolumeUid: MetricKey.OfString = MetricKey.OfString("k8s.persistentvolume.uid")
        public val persistentvolumeclaimName: MetricKey.OfString = MetricKey.OfString("k8s.persistentvolumeclaim.name")
        public val persistentvolumeclaimStatusPhase: MetricKey.OfString = MetricKey.OfString("k8s.persistentvolumeclaim.status.phase")
        public val persistentvolumeclaimUid: MetricKey.OfString = MetricKey.OfString("k8s.persistentvolumeclaim.uid")
        public val podHostname: MetricKey.OfString = MetricKey.OfString("k8s.pod.hostname")
        public val podIp: MetricKey.OfString = MetricKey.OfString("k8s.pod.ip")
        public val podName: MetricKey.OfString = MetricKey.OfString("k8s.pod.name")
        public val podStartTime: MetricKey.OfString = MetricKey.OfString("k8s.pod.start_time")
        public val podStatusPhase: MetricKey.OfString = MetricKey.OfString("k8s.pod.status.phase")
        public val podStatusReason: MetricKey.OfString = MetricKey.OfString("k8s.pod.status.reason")
        public val podUid: MetricKey.OfString = MetricKey.OfString("k8s.pod.uid")
        public val replicasetName: MetricKey.OfString = MetricKey.OfString("k8s.replicaset.name")
        public val replicasetUid: MetricKey.OfString = MetricKey.OfString("k8s.replicaset.uid")
        public val replicationcontrollerName: MetricKey.OfString = MetricKey.OfString("k8s.replicationcontroller.name")
        public val replicationcontrollerUid: MetricKey.OfString = MetricKey.OfString("k8s.replicationcontroller.uid")
        public val resourcequotaName: MetricKey.OfString = MetricKey.OfString("k8s.resourcequota.name")
        public val resourcequotaResourceName: MetricKey.OfString = MetricKey.OfString("k8s.resourcequota.resource_name")
        public val resourcequotaUid: MetricKey.OfString = MetricKey.OfString("k8s.resourcequota.uid")
        public val serviceEndpointAddressType: MetricKey.OfString = MetricKey.OfString("k8s.service.endpoint.address_type")
        public val serviceEndpointCondition: MetricKey.OfString = MetricKey.OfString("k8s.service.endpoint.condition")
        public val serviceEndpointZone: MetricKey.OfString = MetricKey.OfString("k8s.service.endpoint.zone")
        public val serviceName: MetricKey.OfString = MetricKey.OfString("k8s.service.name")
        public val servicePublishNotReadyAddresses: MetricKey.OfBoolean = MetricKey.OfBoolean("k8s.service.publish_not_ready_addresses")
        public val serviceTrafficDistribution: MetricKey.OfString = MetricKey.OfString("k8s.service.traffic_distribution")
        public val serviceType: MetricKey.OfString = MetricKey.OfString("k8s.service.type")
        public val serviceUid: MetricKey.OfString = MetricKey.OfString("k8s.service.uid")
        public val statefulsetName: MetricKey.OfString = MetricKey.OfString("k8s.statefulset.name")
        public val statefulsetUid: MetricKey.OfString = MetricKey.OfString("k8s.statefulset.uid")
        public val storageclassName: MetricKey.OfString = MetricKey.OfString("k8s.storageclass.name")
        public val volumeName: MetricKey.OfString = MetricKey.OfString("k8s.volume.name")
        public val volumeType: MetricKey.OfString = MetricKey.OfString("k8s.volume.type")
    }
    public object Linux {
        public val memorySlabState: MetricKey.OfString = MetricKey.OfString("linux.memory.slab.state")
    }
    public object Log {
        public val fileName: MetricKey.OfString = MetricKey.OfString("log.file.name")
        public val fileNameResolved: MetricKey.OfString = MetricKey.OfString("log.file.name_resolved")
        public val filePath: MetricKey.OfString = MetricKey.OfString("log.file.path")
        public val filePathResolved: MetricKey.OfString = MetricKey.OfString("log.file.path_resolved")
        public val iostream: MetricKey.OfString = MetricKey.OfString("log.iostream")
        public val recordOriginal: MetricKey.OfString = MetricKey.OfString("log.record.original")
        public val recordUid: MetricKey.OfString = MetricKey.OfString("log.record.uid")
    }
    public object Mainframe {
        public val lparName: MetricKey.OfString = MetricKey.OfString("mainframe.lpar.name")
    }
    public object Mcp {
        public val methodName: MetricKey.OfString = MetricKey.OfString("mcp.method.name")
        public val protocolVersion: MetricKey.OfString = MetricKey.OfString("mcp.protocol.version")
        public val resourceUri: MetricKey.OfString = MetricKey.OfString("mcp.resource.uri")
        public val sessionId: MetricKey.OfString = MetricKey.OfString("mcp.session.id")
    }
    public object Message {
        public val compressedSize: MetricKey.OfLong = MetricKey.OfLong("message.compressed_size")
        public val id: MetricKey.OfLong = MetricKey.OfLong("message.id")
        public val type: MetricKey.OfString = MetricKey.OfString("message.type")
        public val uncompressedSize: MetricKey.OfLong = MetricKey.OfLong("message.uncompressed_size")
    }
    public object Messaging {
        public val batchMessageCount: MetricKey.OfLong = MetricKey.OfLong("messaging.batch.message_count")
        public val clientId: MetricKey.OfString = MetricKey.OfString("messaging.client_id")
        public val consumerGroupName: MetricKey.OfString = MetricKey.OfString("messaging.consumer.group.name")
        public val destinationAnonymous: MetricKey.OfBoolean = MetricKey.OfBoolean("messaging.destination.anonymous")
        public val destinationName: MetricKey.OfString = MetricKey.OfString("messaging.destination.name")
        public val destinationPartitionId: MetricKey.OfString = MetricKey.OfString("messaging.destination.partition.id")
        public val destinationSubscriptionName: MetricKey.OfString = MetricKey.OfString("messaging.destination.subscription.name")
        public val destinationTemplate: MetricKey.OfString = MetricKey.OfString("messaging.destination.template")
        public val destinationTemporary: MetricKey.OfBoolean = MetricKey.OfBoolean("messaging.destination.temporary")
        public val destinationPublishAnonymous: MetricKey.OfBoolean = MetricKey.OfBoolean("messaging.destination_publish.anonymous")
        public val destinationPublishName: MetricKey.OfString = MetricKey.OfString("messaging.destination_publish.name")
        public val eventhubsConsumerGroup: MetricKey.OfString = MetricKey.OfString("messaging.eventhubs.consumer.group")
        public val eventhubsMessageEnqueuedTime: MetricKey.OfLong = MetricKey.OfLong("messaging.eventhubs.message.enqueued_time")
        public val gcpPubsubMessageAckDeadline: MetricKey.OfLong = MetricKey.OfLong("messaging.gcp_pubsub.message.ack_deadline")
        public val gcpPubsubMessageAckId: MetricKey.OfString = MetricKey.OfString("messaging.gcp_pubsub.message.ack_id")
        public val gcpPubsubMessageDeliveryAttempt: MetricKey.OfLong = MetricKey.OfLong("messaging.gcp_pubsub.message.delivery_attempt")
        public val gcpPubsubMessageOrderingKey: MetricKey.OfString = MetricKey.OfString("messaging.gcp_pubsub.message.ordering_key")
        public val kafkaConsumerGroup: MetricKey.OfString = MetricKey.OfString("messaging.kafka.consumer.group")
        public val kafkaDestinationPartition: MetricKey.OfLong = MetricKey.OfLong("messaging.kafka.destination.partition")
        public val kafkaMessageKey: MetricKey.OfString = MetricKey.OfString("messaging.kafka.message.key")
        public val kafkaMessageOffset: MetricKey.OfLong = MetricKey.OfLong("messaging.kafka.message.offset")
        public val kafkaMessageTombstone: MetricKey.OfBoolean = MetricKey.OfBoolean("messaging.kafka.message.tombstone")
        public val kafkaOffset: MetricKey.OfLong = MetricKey.OfLong("messaging.kafka.offset")
        public val messageBodySize: MetricKey.OfLong = MetricKey.OfLong("messaging.message.body.size")
        public val messageConversationId: MetricKey.OfString = MetricKey.OfString("messaging.message.conversation_id")
        public val messageEnvelopeSize: MetricKey.OfLong = MetricKey.OfLong("messaging.message.envelope.size")
        public val messageId: MetricKey.OfString = MetricKey.OfString("messaging.message.id")
        public val operation: MetricKey.OfString = MetricKey.OfString("messaging.operation")
        public val operationName: MetricKey.OfString = MetricKey.OfString("messaging.operation.name")
        public val operationType: MetricKey.OfString = MetricKey.OfString("messaging.operation.type")
        public val rabbitmqDestinationRoutingKey: MetricKey.OfString = MetricKey.OfString("messaging.rabbitmq.destination.routing_key")
        public val rabbitmqMessageDeliveryTag: MetricKey.OfLong = MetricKey.OfLong("messaging.rabbitmq.message.delivery_tag")
        public val rocketmqClientGroup: MetricKey.OfString = MetricKey.OfString("messaging.rocketmq.client_group")
        public val rocketmqConsumptionModel: MetricKey.OfString = MetricKey.OfString("messaging.rocketmq.consumption_model")
        public val rocketmqMessageDelayTimeLevel: MetricKey.OfLong = MetricKey.OfLong("messaging.rocketmq.message.delay_time_level")
        public val rocketmqMessageDeliveryTimestamp: MetricKey.OfLong = MetricKey.OfLong("messaging.rocketmq.message.delivery_timestamp")
        public val rocketmqMessageGroup: MetricKey.OfString = MetricKey.OfString("messaging.rocketmq.message.group")
        public val rocketmqMessageKeys: MetricKey.OfStringList = MetricKey.OfStringList("messaging.rocketmq.message.keys")
        public val rocketmqMessageTag: MetricKey.OfString = MetricKey.OfString("messaging.rocketmq.message.tag")
        public val rocketmqMessageType: MetricKey.OfString = MetricKey.OfString("messaging.rocketmq.message.type")
        public val rocketmqNamespace: MetricKey.OfString = MetricKey.OfString("messaging.rocketmq.namespace")
        public val servicebusDestinationSubscriptionName: MetricKey.OfString = MetricKey.OfString("messaging.servicebus.destination.subscription_name")
        public val servicebusDispositionStatus: MetricKey.OfString = MetricKey.OfString("messaging.servicebus.disposition_status")
        public val servicebusMessageDeliveryCount: MetricKey.OfLong = MetricKey.OfLong("messaging.servicebus.message.delivery_count")
        public val servicebusMessageEnqueuedTime: MetricKey.OfLong = MetricKey.OfLong("messaging.servicebus.message.enqueued_time")
        public val system: MetricKey.OfString = MetricKey.OfString("messaging.system")
    }
    public object Net {
        public val hostIp: MetricKey.OfString = MetricKey.OfString("net.host.ip")
        public val hostName: MetricKey.OfString = MetricKey.OfString("net.host.name")
        public val hostPort: MetricKey.OfLong = MetricKey.OfLong("net.host.port")
        public val peerIp: MetricKey.OfString = MetricKey.OfString("net.peer.ip")
        public val peerName: MetricKey.OfString = MetricKey.OfString("net.peer.name")
        public val peerPort: MetricKey.OfLong = MetricKey.OfLong("net.peer.port")
        public val protocolName: MetricKey.OfString = MetricKey.OfString("net.protocol.name")
        public val protocolVersion: MetricKey.OfString = MetricKey.OfString("net.protocol.version")
        public val sockFamily: MetricKey.OfString = MetricKey.OfString("net.sock.family")
        public val sockHostAddr: MetricKey.OfString = MetricKey.OfString("net.sock.host.addr")
        public val sockHostPort: MetricKey.OfLong = MetricKey.OfLong("net.sock.host.port")
        public val sockPeerAddr: MetricKey.OfString = MetricKey.OfString("net.sock.peer.addr")
        public val sockPeerName: MetricKey.OfString = MetricKey.OfString("net.sock.peer.name")
        public val sockPeerPort: MetricKey.OfLong = MetricKey.OfLong("net.sock.peer.port")
        public val transport: MetricKey.OfString = MetricKey.OfString("net.transport")
    }
    public object Network {
        public val carrierIcc: MetricKey.OfString = MetricKey.OfString("network.carrier.icc")
        public val carrierMcc: MetricKey.OfString = MetricKey.OfString("network.carrier.mcc")
        public val carrierMnc: MetricKey.OfString = MetricKey.OfString("network.carrier.mnc")
        public val carrierName: MetricKey.OfString = MetricKey.OfString("network.carrier.name")
        public val connectionState: MetricKey.OfString = MetricKey.OfString("network.connection.state")
        public val connectionSubtype: MetricKey.OfString = MetricKey.OfString("network.connection.subtype")
        public val connectionType: MetricKey.OfString = MetricKey.OfString("network.connection.type")
        public val interfaceName: MetricKey.OfString = MetricKey.OfString("network.interface.name")
        public val ioDirection: MetricKey.OfString = MetricKey.OfString("network.io.direction")
        public val localAddress: MetricKey.OfString = MetricKey.OfString("network.local.address")
        public val localPort: MetricKey.OfLong = MetricKey.OfLong("network.local.port")
        public val peerAddress: MetricKey.OfString = MetricKey.OfString("network.peer.address")
        public val peerPort: MetricKey.OfLong = MetricKey.OfLong("network.peer.port")
        public val protocolName: MetricKey.OfString = MetricKey.OfString("network.protocol.name")
        public val protocolVersion: MetricKey.OfString = MetricKey.OfString("network.protocol.version")
        public val transport: MetricKey.OfString = MetricKey.OfString("network.transport")
        public val type: MetricKey.OfString = MetricKey.OfString("network.type")
    }
    public object Nfs {
        public val operationName: MetricKey.OfString = MetricKey.OfString("nfs.operation.name")
        public val serverRepcacheStatus: MetricKey.OfString = MetricKey.OfString("nfs.server.repcache.status")
    }
    public object Nodejs {
        public val eventloopState: MetricKey.OfString = MetricKey.OfString("nodejs.eventloop.state")
    }
    public object Oci {
        public val manifestDigest: MetricKey.OfString = MetricKey.OfString("oci.manifest.digest")
    }
    public object OncRpc {
        public val procedureName: MetricKey.OfString = MetricKey.OfString("onc_rpc.procedure.name")
        public val procedureNumber: MetricKey.OfLong = MetricKey.OfLong("onc_rpc.procedure.number")
        public val programName: MetricKey.OfString = MetricKey.OfString("onc_rpc.program.name")
        public val version: MetricKey.OfLong = MetricKey.OfLong("onc_rpc.version")
    }
    public object Openai {
        public val apiType: MetricKey.OfString = MetricKey.OfString("openai.api.type")
        public val requestServiceTier: MetricKey.OfString = MetricKey.OfString("openai.request.service_tier")
        public val responseServiceTier: MetricKey.OfString = MetricKey.OfString("openai.response.service_tier")
        public val responseSystemFingerprint: MetricKey.OfString = MetricKey.OfString("openai.response.system_fingerprint")
    }
    public object Openshift {
        public val clusterquotaName: MetricKey.OfString = MetricKey.OfString("openshift.clusterquota.name")
        public val clusterquotaUid: MetricKey.OfString = MetricKey.OfString("openshift.clusterquota.uid")
    }
    public object Opentracing {
        public val refType: MetricKey.OfString = MetricKey.OfString("opentracing.ref_type")
    }
    public object Oracle {
        public val dbDomain: MetricKey.OfString = MetricKey.OfString("oracle.db.domain")
        public val dbInstanceName: MetricKey.OfString = MetricKey.OfString("oracle.db.instance.name")
        public val dbName: MetricKey.OfString = MetricKey.OfString("oracle.db.name")
        public val dbPdb: MetricKey.OfString = MetricKey.OfString("oracle.db.pdb")
        public val dbService: MetricKey.OfString = MetricKey.OfString("oracle.db.service")
    }
    public object OracleCloud {
        public val realm: MetricKey.OfString = MetricKey.OfString("oracle_cloud.realm")
    }
    public object Os {
        public val buildId: MetricKey.OfString = MetricKey.OfString("os.build_id")
        public val description: MetricKey.OfString = MetricKey.OfString("os.description")
        public val name: MetricKey.OfString = MetricKey.OfString("os.name")
        public val type: MetricKey.OfString = MetricKey.OfString("os.type")
        public val version: MetricKey.OfString = MetricKey.OfString("os.version")
    }
    public object Otel {
        public val componentName: MetricKey.OfString = MetricKey.OfString("otel.component.name")
        public val componentType: MetricKey.OfString = MetricKey.OfString("otel.component.type")
        public val eventName: MetricKey.OfString = MetricKey.OfString("otel.event.name")
        public val libraryName: MetricKey.OfString = MetricKey.OfString("otel.library.name")
        public val libraryVersion: MetricKey.OfString = MetricKey.OfString("otel.library.version")
        public val scopeName: MetricKey.OfString = MetricKey.OfString("otel.scope.name")
        public val scopeSchemaUrl: MetricKey.OfString = MetricKey.OfString("otel.scope.schema_url")
        public val scopeVersion: MetricKey.OfString = MetricKey.OfString("otel.scope.version")
        public val spanParentOrigin: MetricKey.OfString = MetricKey.OfString("otel.span.parent.origin")
        public val spanSamplingResult: MetricKey.OfString = MetricKey.OfString("otel.span.sampling_result")
        public val statusCode: MetricKey.OfString = MetricKey.OfString("otel.status_code")
        public val statusDescription: MetricKey.OfString = MetricKey.OfString("otel.status_description")
    }
    public object Peer {
        public val service: MetricKey.OfString = MetricKey.OfString("peer.service")
    }
    public object Pool {
        public val name: MetricKey.OfString = MetricKey.OfString("pool.name")
    }
    public object Pprof {
        public val locationIsFolded: MetricKey.OfBoolean = MetricKey.OfBoolean("pprof.location.is_folded")
        public val mappingHasFilenames: MetricKey.OfBoolean = MetricKey.OfBoolean("pprof.mapping.has_filenames")
        public val mappingHasFunctions: MetricKey.OfBoolean = MetricKey.OfBoolean("pprof.mapping.has_functions")
        public val mappingHasInlineFrames: MetricKey.OfBoolean = MetricKey.OfBoolean("pprof.mapping.has_inline_frames")
        public val mappingHasLineNumbers: MetricKey.OfBoolean = MetricKey.OfBoolean("pprof.mapping.has_line_numbers")
        public val profileComment: MetricKey.OfStringList = MetricKey.OfStringList("pprof.profile.comment")
        public val profileDocUrl: MetricKey.OfString = MetricKey.OfString("pprof.profile.doc_url")
        public val profileDropFrames: MetricKey.OfString = MetricKey.OfString("pprof.profile.drop_frames")
        public val profileKeepFrames: MetricKey.OfString = MetricKey.OfString("pprof.profile.keep_frames")
        public val scopeDefaultSampleType: MetricKey.OfString = MetricKey.OfString("pprof.scope.default_sample_type")
    }
    public object Process {
        public val argsCount: MetricKey.OfLong = MetricKey.OfLong("process.args_count")
        public val command: MetricKey.OfString = MetricKey.OfString("process.command")
        public val commandArgs: MetricKey.OfStringList = MetricKey.OfStringList("process.command_args")
        public val commandLine: MetricKey.OfString = MetricKey.OfString("process.command_line")
        public val contextSwitchType: MetricKey.OfString = MetricKey.OfString("process.context_switch_type")
        public val cpuState: MetricKey.OfString = MetricKey.OfString("process.cpu.state")
        public val creationTime: MetricKey.OfString = MetricKey.OfString("process.creation.time")
        public val executableBuildIdGnu: MetricKey.OfString = MetricKey.OfString("process.executable.build_id.gnu")
        public val executableBuildIdGo: MetricKey.OfString = MetricKey.OfString("process.executable.build_id.go")
        public val executableBuildIdHtlhash: MetricKey.OfString = MetricKey.OfString("process.executable.build_id.htlhash")
        public val executableBuildIdProfiling: MetricKey.OfString = MetricKey.OfString("process.executable.build_id.profiling")
        public val executableName: MetricKey.OfString = MetricKey.OfString("process.executable.name")
        public val executablePath: MetricKey.OfString = MetricKey.OfString("process.executable.path")
        public val exitCode: MetricKey.OfLong = MetricKey.OfLong("process.exit.code")
        public val exitTime: MetricKey.OfString = MetricKey.OfString("process.exit.time")
        public val groupLeaderPid: MetricKey.OfLong = MetricKey.OfLong("process.group_leader.pid")
        public val interactive: MetricKey.OfBoolean = MetricKey.OfBoolean("process.interactive")
        public val linuxCgroup: MetricKey.OfString = MetricKey.OfString("process.linux.cgroup")
        public val owner: MetricKey.OfString = MetricKey.OfString("process.owner")
        public val pagingFaultType: MetricKey.OfString = MetricKey.OfString("process.paging.fault_type")
        public val parentPid: MetricKey.OfLong = MetricKey.OfLong("process.parent_pid")
        public val pid: MetricKey.OfLong = MetricKey.OfLong("process.pid")
        public val realUserId: MetricKey.OfLong = MetricKey.OfLong("process.real_user.id")
        public val realUserName: MetricKey.OfString = MetricKey.OfString("process.real_user.name")
        public val runtimeDescription: MetricKey.OfString = MetricKey.OfString("process.runtime.description")
        public val runtimeName: MetricKey.OfString = MetricKey.OfString("process.runtime.name")
        public val runtimeVersion: MetricKey.OfString = MetricKey.OfString("process.runtime.version")
        public val savedUserId: MetricKey.OfLong = MetricKey.OfLong("process.saved_user.id")
        public val savedUserName: MetricKey.OfString = MetricKey.OfString("process.saved_user.name")
        public val sessionLeaderPid: MetricKey.OfLong = MetricKey.OfLong("process.session_leader.pid")
        public val state: MetricKey.OfString = MetricKey.OfString("process.state")
        public val title: MetricKey.OfString = MetricKey.OfString("process.title")
        public val userId: MetricKey.OfLong = MetricKey.OfLong("process.user.id")
        public val userName: MetricKey.OfString = MetricKey.OfString("process.user.name")
        public val vpid: MetricKey.OfLong = MetricKey.OfLong("process.vpid")
        public val workingDirectory: MetricKey.OfString = MetricKey.OfString("process.working_directory")
    }
    public object Profile {
        public val frameType: MetricKey.OfString = MetricKey.OfString("profile.frame.type")
    }
    public object Rpc {
        public val connectRpcErrorCode: MetricKey.OfString = MetricKey.OfString("rpc.connect_rpc.error_code")
        public val grpcStatusCode: MetricKey.OfString = MetricKey.OfString("rpc.grpc.status_code")
        public val jsonrpcErrorCode: MetricKey.OfLong = MetricKey.OfLong("rpc.jsonrpc.error_code")
        public val jsonrpcErrorMessage: MetricKey.OfString = MetricKey.OfString("rpc.jsonrpc.error_message")
        public val jsonrpcRequestId: MetricKey.OfString = MetricKey.OfString("rpc.jsonrpc.request_id")
        public val jsonrpcVersion: MetricKey.OfString = MetricKey.OfString("rpc.jsonrpc.version")
        public val messageCompressedSize: MetricKey.OfLong = MetricKey.OfLong("rpc.message.compressed_size")
        public val messageId: MetricKey.OfLong = MetricKey.OfLong("rpc.message.id")
        public val messageType: MetricKey.OfString = MetricKey.OfString("rpc.message.type")
        public val messageUncompressedSize: MetricKey.OfLong = MetricKey.OfLong("rpc.message.uncompressed_size")
        public val method: MetricKey.OfString = MetricKey.OfString("rpc.method")
        public val methodOriginal: MetricKey.OfString = MetricKey.OfString("rpc.method_original")
        public val responseStatusCode: MetricKey.OfString = MetricKey.OfString("rpc.response.status_code")
        public val service: MetricKey.OfString = MetricKey.OfString("rpc.service")
        public val system: MetricKey.OfString = MetricKey.OfString("rpc.system")
        public val systemName: MetricKey.OfString = MetricKey.OfString("rpc.system.name")
    }
    public object SecurityRule {
        public val category: MetricKey.OfString = MetricKey.OfString("security_rule.category")
        public val description: MetricKey.OfString = MetricKey.OfString("security_rule.description")
        public val license: MetricKey.OfString = MetricKey.OfString("security_rule.license")
        public val name: MetricKey.OfString = MetricKey.OfString("security_rule.name")
        public val reference: MetricKey.OfString = MetricKey.OfString("security_rule.reference")
        public val rulesetName: MetricKey.OfString = MetricKey.OfString("security_rule.ruleset.name")
        public val uuid: MetricKey.OfString = MetricKey.OfString("security_rule.uuid")
        public val version: MetricKey.OfString = MetricKey.OfString("security_rule.version")
    }
    public object Server {
        public val address: MetricKey.OfString = MetricKey.OfString("server.address")
        public val port: MetricKey.OfLong = MetricKey.OfLong("server.port")
    }
    public object Service {
        public val criticality: MetricKey.OfString = MetricKey.OfString("service.criticality")
        public val instanceId: MetricKey.OfString = MetricKey.OfString("service.instance.id")
        public val name: MetricKey.OfString = MetricKey.OfString("service.name")
        public val namespace: MetricKey.OfString = MetricKey.OfString("service.namespace")
        public val peerName: MetricKey.OfString = MetricKey.OfString("service.peer.name")
        public val peerNamespace: MetricKey.OfString = MetricKey.OfString("service.peer.namespace")
        public val version: MetricKey.OfString = MetricKey.OfString("service.version")
    }
    public object Session {
        public val id: MetricKey.OfString = MetricKey.OfString("session.id")
        public val previousId: MetricKey.OfString = MetricKey.OfString("session.previous_id")
    }
    public object Signalr {
        public val connectionStatus: MetricKey.OfString = MetricKey.OfString("signalr.connection.status")
        public val transport: MetricKey.OfString = MetricKey.OfString("signalr.transport")
    }
    public object Source {
        public val address: MetricKey.OfString = MetricKey.OfString("source.address")
        public val port: MetricKey.OfLong = MetricKey.OfLong("source.port")
    }
    public val state: MetricKey.OfString = MetricKey.OfString("state")
    public object System {
        public val cpuLogicalNumber: MetricKey.OfLong = MetricKey.OfLong("system.cpu.logical_number")
        public val cpuState: MetricKey.OfString = MetricKey.OfString("system.cpu.state")
        public val device: MetricKey.OfString = MetricKey.OfString("system.device")
        public val filesystemMode: MetricKey.OfString = MetricKey.OfString("system.filesystem.mode")
        public val filesystemMountpoint: MetricKey.OfString = MetricKey.OfString("system.filesystem.mountpoint")
        public val filesystemState: MetricKey.OfString = MetricKey.OfString("system.filesystem.state")
        public val filesystemType: MetricKey.OfString = MetricKey.OfString("system.filesystem.type")
        public val memoryLinuxHugepagesState: MetricKey.OfString = MetricKey.OfString("system.memory.linux.hugepages.state")
        public val memoryLinuxSlabState: MetricKey.OfString = MetricKey.OfString("system.memory.linux.slab.state")
        public val memoryState: MetricKey.OfString = MetricKey.OfString("system.memory.state")
        public val networkState: MetricKey.OfString = MetricKey.OfString("system.network.state")
        public val pagingDirection: MetricKey.OfString = MetricKey.OfString("system.paging.direction")
        public val pagingFaultType: MetricKey.OfString = MetricKey.OfString("system.paging.fault.type")
        public val pagingState: MetricKey.OfString = MetricKey.OfString("system.paging.state")
        public val pagingType: MetricKey.OfString = MetricKey.OfString("system.paging.type")
        public val processStatus: MetricKey.OfString = MetricKey.OfString("system.process.status")
        public val processesStatus: MetricKey.OfString = MetricKey.OfString("system.processes.status")
    }
    public object Telemetry {
        public val distroName: MetricKey.OfString = MetricKey.OfString("telemetry.distro.name")
        public val distroVersion: MetricKey.OfString = MetricKey.OfString("telemetry.distro.version")
        public val sdkLanguage: MetricKey.OfString = MetricKey.OfString("telemetry.sdk.language")
        public val sdkName: MetricKey.OfString = MetricKey.OfString("telemetry.sdk.name")
        public val sdkVersion: MetricKey.OfString = MetricKey.OfString("telemetry.sdk.version")
    }
    public object Test {
        public val caseName: MetricKey.OfString = MetricKey.OfString("test.case.name")
        public val caseResultStatus: MetricKey.OfString = MetricKey.OfString("test.case.result.status")
        public val suiteName: MetricKey.OfString = MetricKey.OfString("test.suite.name")
        public val suiteRunStatus: MetricKey.OfString = MetricKey.OfString("test.suite.run.status")
    }
    public object Thread {
        public val id: MetricKey.OfLong = MetricKey.OfLong("thread.id")
        public val name: MetricKey.OfString = MetricKey.OfString("thread.name")
    }
    public object Tls {
        public val cipher: MetricKey.OfString = MetricKey.OfString("tls.cipher")
        public val clientCertificate: MetricKey.OfString = MetricKey.OfString("tls.client.certificate")
        public val clientCertificateChain: MetricKey.OfStringList = MetricKey.OfStringList("tls.client.certificate_chain")
        public val clientHashMd5: MetricKey.OfString = MetricKey.OfString("tls.client.hash.md5")
        public val clientHashSha1: MetricKey.OfString = MetricKey.OfString("tls.client.hash.sha1")
        public val clientHashSha256: MetricKey.OfString = MetricKey.OfString("tls.client.hash.sha256")
        public val clientIssuer: MetricKey.OfString = MetricKey.OfString("tls.client.issuer")
        public val clientJa3: MetricKey.OfString = MetricKey.OfString("tls.client.ja3")
        public val clientNotAfter: MetricKey.OfString = MetricKey.OfString("tls.client.not_after")
        public val clientNotBefore: MetricKey.OfString = MetricKey.OfString("tls.client.not_before")
        public val clientServerName: MetricKey.OfString = MetricKey.OfString("tls.client.server_name")
        public val clientSubject: MetricKey.OfString = MetricKey.OfString("tls.client.subject")
        public val clientSupportedCiphers: MetricKey.OfStringList = MetricKey.OfStringList("tls.client.supported_ciphers")
        public val curve: MetricKey.OfString = MetricKey.OfString("tls.curve")
        public val established: MetricKey.OfBoolean = MetricKey.OfBoolean("tls.established")
        public val nextProtocol: MetricKey.OfString = MetricKey.OfString("tls.next_protocol")
        public val protocolName: MetricKey.OfString = MetricKey.OfString("tls.protocol.name")
        public val protocolVersion: MetricKey.OfString = MetricKey.OfString("tls.protocol.version")
        public val resumed: MetricKey.OfBoolean = MetricKey.OfBoolean("tls.resumed")
        public val serverCertificate: MetricKey.OfString = MetricKey.OfString("tls.server.certificate")
        public val serverCertificateChain: MetricKey.OfStringList = MetricKey.OfStringList("tls.server.certificate_chain")
        public val serverHashMd5: MetricKey.OfString = MetricKey.OfString("tls.server.hash.md5")
        public val serverHashSha1: MetricKey.OfString = MetricKey.OfString("tls.server.hash.sha1")
        public val serverHashSha256: MetricKey.OfString = MetricKey.OfString("tls.server.hash.sha256")
        public val serverIssuer: MetricKey.OfString = MetricKey.OfString("tls.server.issuer")
        public val serverJa3s: MetricKey.OfString = MetricKey.OfString("tls.server.ja3s")
        public val serverNotAfter: MetricKey.OfString = MetricKey.OfString("tls.server.not_after")
        public val serverNotBefore: MetricKey.OfString = MetricKey.OfString("tls.server.not_before")
        public val serverSubject: MetricKey.OfString = MetricKey.OfString("tls.server.subject")
    }
    public object Url {
        public val domain: MetricKey.OfString = MetricKey.OfString("url.domain")
        public val extension: MetricKey.OfString = MetricKey.OfString("url.extension")
        public val fragment: MetricKey.OfString = MetricKey.OfString("url.fragment")
        public val full: MetricKey.OfString = MetricKey.OfString("url.full")
        public val original: MetricKey.OfString = MetricKey.OfString("url.original")
        public val path: MetricKey.OfString = MetricKey.OfString("url.path")
        public val port: MetricKey.OfLong = MetricKey.OfLong("url.port")
        public val query: MetricKey.OfString = MetricKey.OfString("url.query")
        public val registeredDomain: MetricKey.OfString = MetricKey.OfString("url.registered_domain")
        public val scheme: MetricKey.OfString = MetricKey.OfString("url.scheme")
        public val subdomain: MetricKey.OfString = MetricKey.OfString("url.subdomain")
        public val template: MetricKey.OfString = MetricKey.OfString("url.template")
        public val topLevelDomain: MetricKey.OfString = MetricKey.OfString("url.top_level_domain")
    }
    public object User {
        public val email: MetricKey.OfString = MetricKey.OfString("user.email")
        public val fullName: MetricKey.OfString = MetricKey.OfString("user.full_name")
        public val hash: MetricKey.OfString = MetricKey.OfString("user.hash")
        public val id: MetricKey.OfString = MetricKey.OfString("user.id")
        public val name: MetricKey.OfString = MetricKey.OfString("user.name")
        public val roles: MetricKey.OfStringList = MetricKey.OfStringList("user.roles")
    }
    public object UserAgent {
        public val name: MetricKey.OfString = MetricKey.OfString("user_agent.name")
        public val original: MetricKey.OfString = MetricKey.OfString("user_agent.original")
        public val osName: MetricKey.OfString = MetricKey.OfString("user_agent.os.name")
        public val osVersion: MetricKey.OfString = MetricKey.OfString("user_agent.os.version")
        public val syntheticType: MetricKey.OfString = MetricKey.OfString("user_agent.synthetic.type")
        public val version: MetricKey.OfString = MetricKey.OfString("user_agent.version")
    }
    public object V8js {
        public val gcType: MetricKey.OfString = MetricKey.OfString("v8js.gc.type")
        public val heapSpaceName: MetricKey.OfString = MetricKey.OfString("v8js.heap.space.name")
        public val resourceType: MetricKey.OfString = MetricKey.OfString("v8js.resource.type")
    }
    public object Vcs {
        public val changeId: MetricKey.OfString = MetricKey.OfString("vcs.change.id")
        public val changeState: MetricKey.OfString = MetricKey.OfString("vcs.change.state")
        public val changeTitle: MetricKey.OfString = MetricKey.OfString("vcs.change.title")
        public val lineChangeType: MetricKey.OfString = MetricKey.OfString("vcs.line_change.type")
        public val ownerName: MetricKey.OfString = MetricKey.OfString("vcs.owner.name")
        public val providerName: MetricKey.OfString = MetricKey.OfString("vcs.provider.name")
        public val refBaseName: MetricKey.OfString = MetricKey.OfString("vcs.ref.base.name")
        public val refBaseRevision: MetricKey.OfString = MetricKey.OfString("vcs.ref.base.revision")
        public val refBaseType: MetricKey.OfString = MetricKey.OfString("vcs.ref.base.type")
        public val refHeadName: MetricKey.OfString = MetricKey.OfString("vcs.ref.head.name")
        public val refHeadRevision: MetricKey.OfString = MetricKey.OfString("vcs.ref.head.revision")
        public val refHeadType: MetricKey.OfString = MetricKey.OfString("vcs.ref.head.type")
        public val refType: MetricKey.OfString = MetricKey.OfString("vcs.ref.type")
        public val repositoryChangeId: MetricKey.OfString = MetricKey.OfString("vcs.repository.change.id")
        public val repositoryChangeTitle: MetricKey.OfString = MetricKey.OfString("vcs.repository.change.title")
        public val repositoryName: MetricKey.OfString = MetricKey.OfString("vcs.repository.name")
        public val repositoryRefName: MetricKey.OfString = MetricKey.OfString("vcs.repository.ref.name")
        public val repositoryRefRevision: MetricKey.OfString = MetricKey.OfString("vcs.repository.ref.revision")
        public val repositoryRefType: MetricKey.OfString = MetricKey.OfString("vcs.repository.ref.type")
        public val repositoryUrlFull: MetricKey.OfString = MetricKey.OfString("vcs.repository.url.full")
        public val revisionDeltaDirection: MetricKey.OfString = MetricKey.OfString("vcs.revision_delta.direction")
    }
    public object Webengine {
        public val description: MetricKey.OfString = MetricKey.OfString("webengine.description")
        public val name: MetricKey.OfString = MetricKey.OfString("webengine.name")
        public val version: MetricKey.OfString = MetricKey.OfString("webengine.version")
    }
    public object Zos {
        public val smfId: MetricKey.OfString = MetricKey.OfString("zos.smf.id")
        public val sysplexName: MetricKey.OfString = MetricKey.OfString("zos.sysplex.name")
    }
}